/* ============================================================
 * 女佣中餐助手 — 菜谱数据库
 * ------------------------------------------------------------
 * 约定（务必遵守）：
 * 1. 所有菜谱按 2 人份为基准，食材数量一律用"个数"，禁用克/斤等重量单位。
 * 2. 印尼语量词存在 INGREDIENT_PRESETS.unitId：butir(蛋/圆形)、ekor(鱼虾整只)、
 *    buah(蔬果个体)、siung(蒜瓣)、batang(长条)、potong(肉块)、lembar(片)、
 *    genggam(一把)、mangkuk(碗)、keping(面饼)、ruas(姜块)。
 * 3. 调料默认家里常备（见 ALWAYS_HAVE），菜谱里用"勺"计量：
 *    1 sendok makan = 1吃饭勺（缩写 sdm），1 sendok teh = 1茶勺（sdt）。
 * 4. 步骤 textId 里的 {食材key} 会在渲染时替换成"数量+量词+印尼语名"，
 *    数量随就餐人数自动缩放，保证文字和长图一致。
 * 5. 步骤写给理解力有限的读者：一句一个动作，有具体数量、火候、分钟数。
 * 6. 每步 textZh / 每菜 tipZh 是给雇主核对用的中文对照，按 2 人份写死，
 *    不用 {key} 占位符。
 * ============================================================ */

/* ---------- 食材预设表（库存选择器用，双语显示） ---------- */
const INGREDIENT_PRESETS = [
  { key: 'egg',         emoji: '🥚', nameZh: '鸡蛋',   nameId: 'telur',          unitId: 'butir'   },
  { key: 'tomato',      emoji: '🍅', nameZh: '番茄',   nameId: 'tomat',          unitId: 'buah'    },
  { key: 'potato',      emoji: '🥔', nameZh: '土豆',   nameId: 'kentang',        unitId: 'buah'    },
  { key: 'chicken_leg', emoji: '🍗', nameZh: '鸡腿',   nameId: 'paha ayam',      unitId: 'potong'  },
  { key: 'chicken_wing',emoji: '🍗', nameZh: '鸡翅',   nameId: 'sayap ayam',     unitId: 'buah'    },
  { key: 'pork',        emoji: '🐷', nameZh: '猪肉',   nameId: 'daging babi',    unitId: 'potong'  },
  { key: 'beef',        emoji: '🐮', nameZh: '牛肉',   nameId: 'daging sapi',    unitId: 'potong'  },
  { key: 'fish',        emoji: '🐟', nameZh: '鱼',     nameId: 'ikan',           unitId: 'ekor'    },
  { key: 'shrimp',      emoji: '🦐', nameZh: '虾',     nameId: 'udang',          unitId: 'ekor'    },
  { key: 'tofu',        emoji: '🫘', nameZh: '豆腐',   nameId: 'tahu',           unitId: 'potong'  },
  { key: 'cucumber',    emoji: '🥒', nameZh: '黄瓜',   nameId: 'timun',          unitId: 'buah'    },
  { key: 'carrot',      emoji: '🥕', nameZh: '胡萝卜', nameId: 'wortel',         unitId: 'buah'    },
  { key: 'eggplant',    emoji: '🍆', nameZh: '茄子',   nameId: 'terong',         unitId: 'buah'    },
  { key: 'bell_pepper', emoji: '🫑', nameZh: '青椒',   nameId: 'paprika hijau',  unitId: 'buah'    },
  { key: 'broccoli',    emoji: '🥦', nameZh: '西兰花', nameId: 'brokoli',        unitId: 'buah'    },
  { key: 'cabbage',     emoji: '🥬', nameZh: '包菜',   nameId: 'kol',            unitId: 'lembar'  },
  { key: 'greens',      emoji: '🥬', nameZh: '青菜',   nameId: 'sawi hijau',     unitId: 'ikat'    },
  { key: 'green_beans', emoji: '🫛', nameZh: '四季豆', nameId: 'buncis',         unitId: 'batang'  },
  { key: 'mushroom',    emoji: '🍄', nameZh: '香菇',   nameId: 'jamur',          unitId: 'buah'    },
  { key: 'corn',        emoji: '🌽', nameZh: '玉米',   nameId: 'jagung',         unitId: 'buah'    },
  { key: 'pumpkin',     emoji: '🎃', nameZh: '南瓜',   nameId: 'labu',           unitId: 'potong'  },
  { key: 'winter_melon',emoji: '🍈', nameZh: '冬瓜',   nameId: 'bligo',          unitId: 'potong'  },
  { key: 'onion',       emoji: '🧅', nameZh: '洋葱',   nameId: 'bawang bombay',  unitId: 'buah'    },
  { key: 'garlic',      emoji: '🧄', nameZh: '大蒜',   nameId: 'bawang putih',   unitId: 'siung'   },
  { key: 'ginger',      emoji: '🫚', nameZh: '姜',     nameId: 'jahe',           unitId: 'ruas'    },
  { key: 'scallion',    emoji: '🌿', nameZh: '葱',     nameId: 'daun bawang',    unitId: 'batang'  },
  { key: 'chili',       emoji: '🌶️', nameZh: '辣椒',   nameId: 'cabai',          unitId: 'buah'    },
  { key: 'peanut',      emoji: '🥜', nameZh: '花生',   nameId: 'kacang tanah',   unitId: 'genggam' },
  { key: 'chives',      emoji: '🌱', nameZh: '韭菜',   nameId: 'kucai',          unitId: 'ikat'    },
  { key: 'laver',       emoji: '🍙', nameZh: '紫菜',   nameId: 'rumput laut kering', unitId: 'lembar' },
  { key: 'rice',        emoji: '🍚', nameZh: '米饭',   nameId: 'nasi',           unitId: 'mangkuk' },
  { key: 'noodles',     emoji: '🍜', nameZh: '面条',   nameId: 'mie kering',     unitId: 'keping'  },
  { key: 'pork_ribs',   emoji: '🍖', nameZh: '排骨',   nameId: 'iga babi',       unitId: 'potong'  },
  { key: 'minced_pork', emoji: '🐷', nameZh: '猪肉末', nameId: 'daging babi cincang', unitId: 'mangkuk' },
  { key: 'cola',        emoji: '🥤', nameZh: '可乐',   nameId: 'cola',           unitId: 'kaleng'  },
  { key: 'pomfret',     emoji: '🐟', nameZh: '白鲳',   nameId: 'ikan bawal',     unitId: 'ekor'    },
  { key: 'hairtail',    emoji: '🐟', nameZh: '带鱼',   nameId: 'ikan layur',     unitId: 'potong'  },
  { key: 'squid',       emoji: '🦑', nameZh: '鱿鱼',   nameId: 'cumi',           unitId: 'ekor'    },
  { key: 'mackerel',    emoji: '🐟', nameZh: '鲅鱼',   nameId: 'ikan tenggiri',  unitId: 'potong'  },
  { key: 'kangkung',    emoji: '🥬', nameZh: '空心菜', nameId: 'kangkung',       unitId: 'ikat'    },
];

/* ---------- 常备调料（不用录入库存，卡片上提示） ---------- */
const ALWAYS_HAVE = [
  { nameZh: '食用油', nameId: 'minyak goreng' },
  { nameZh: '盐',     nameId: 'garam' },
  { nameZh: '生抽',   nameId: 'kecap asin' },
  { nameZh: '蚝油',   nameId: 'saus tiram' },
  { nameZh: '甜酱油', nameId: 'kecap manis' },
  { nameZh: '糖',     nameId: 'gula' },
  { nameZh: '醋',     nameId: 'cuka' },
  { nameZh: '淀粉',   nameId: 'tepung maizena' },
  { nameZh: '胡椒',   nameId: 'merica' },
];

/* ---------- 数量缩放：基准2人份，N人时向上取整、至少为1 ---------- */
function scaledQty(baseQty, persons) {
  const p = Math.max(1, Number(persons) || 2);
  return Math.max(1, Math.ceil(baseQty * p / 2));
}

/* ---------- 印尼语数量文本：scaled -> "3 butir telur" ---------- */
function formatQtyId(key, qty) {
  const ing = INGREDIENT_PRESETS.find(i => i.key === key);
  if (!ing) return qty + ' ' + key;
  return qty + ' ' + ing.unitId + ' ' + ing.nameId;
}

/* ---------- 渲染单步：把 {key} 换成按人数缩放后的数量文本 ---------- */
function renderStepId(recipe, step, persons) {
  return step.textId.replace(/\{(\w+)\}/g, (m, key) => {
    const found = recipe.ingredients.find(i => i.key === key);
    const base = found ? found.qty : 1;
    return formatQtyId(key, scaledQty(base, persons));
  });
}

/* ---------- 菜谱 ----------
 * category 用于"荤素搭配"推荐：chicken/pork/beef/fish/shrimp/egg/tofu/veg/soup
 * difficulty：1 = 简单
 */
const RECIPES = [
  {
    id: 'tomato-egg',
    nameZh: '番茄炒蛋',
    nameId: 'Telur Orak-arik Tomat',
    emoji: '🍅',
    category: 'egg',
    timeMin: 15,
    difficulty: 1,
    ingredients: [
      { key: 'tomato',   qty: 2 },
      { key: 'egg',      qty: 3 },
      { key: 'scallion', qty: 1 },
    ],
    steps: [
      { emoji: '🍅', textId: 'Cuci {tomato}. Potong tiap buah jadi 8 bagian.', textZh: '2个番茄洗净，每个切成8瓣。' },
      { emoji: '🥚', textId: 'Pecahkan {egg} ke dalam mangkuk. Kocok dengan garpu selama 30 detik.', textZh: '3个鸡蛋打入碗里，用叉子搅30秒。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Tunggu 1 menit.', textZh: '烧热锅，倒2饭勺油，等1分钟。' },
      { emoji: '🍳', textId: 'Masukkan telur. Aduk pelan sampai matang. Angkat ke piring.', textZh: '倒入蛋液，轻轻翻炒至熟，盛到盘子里。' },
      { emoji: '🍅', textId: 'Tuang 1 sendok makan minyak lagi. Masukkan tomat. Masak 2 menit dengan api sedang sampai tomat lembek.', textZh: '再倒1饭勺油，放入番茄，中火炒2分钟至软烂。' },
      { emoji: '🧂', textId: 'Masukkan telur kembali. Tambah 1 sendok teh garam dan 1 sendok teh gula. Aduk 1 menit.', textZh: '倒回鸡蛋，加1茶勺盐和1茶勺糖，翻炒1分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Taburi {scallion} yang sudah dipotong kecil.', textZh: '关火出锅，撒上切好的葱花（1根）。' },
    ],
    tipId: 'Kalau tomat kurang manis, tambah sedikit gula lagi.',
    tipZh: '番茄不够甜的话，再加点糖。',
  },
  {
    id: 'kungpao-chicken',
    nameZh: '宫保鸡丁（简化版）',
    nameId: 'Ayam Kung Pao',
    emoji: '🌶️',
    category: 'chicken',
    timeMin: 25,
    difficulty: 1,
    ingredients: [
      { key: 'chicken_leg', qty: 2 },
      { key: 'cucumber',    qty: 1 },
      { key: 'peanut',      qty: 1 },
      { key: 'garlic',      qty: 3 },
      { key: 'ginger',      qty: 1 },
      { key: 'chili',       qty: 2 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Potong {chicken_leg} kecil-kecil, sebesar dadu.', textZh: '2个鸡腿切成小丁。' },
      { emoji: '🧂', textId: 'Taruh ayam di mangkuk. Tambah 1 sendok makan kecap asin dan 1 sendok makan tepung maizena. Aduk rata. Diamkan 10 menit.', textZh: '鸡肉放碗里，加1饭勺生抽和1饭勺淀粉，拌匀，腌10分钟。' },
      { emoji: '🥒', textId: 'Potong {cucumber} sebesar dadu. Geprek dan potong kecil {garlic}. Potong tipis {ginger}.', textZh: '1根黄瓜切丁；3瓣蒜拍碎切小；1块姜切薄片。' },
      { emoji: '🔥', textId: 'Panaskan wajan, tuang 2 sendok makan minyak. Masukkan ayam. Masak 4 menit dengan api sedang sampai berubah warna. Angkat ke piring.', textZh: '烧热锅倒2饭勺油，下鸡肉，中火炒4分钟至变色，盛出。' },
      { emoji: '🌶️', textId: 'Tuang 1 sendok makan minyak. Masukkan bawang putih, jahe, dan {chili}. Aduk 30 detik.', textZh: '倒1饭勺油，下蒜、姜和2个辣椒，炒30秒。' },
      { emoji: '🥒', textId: 'Masukkan timun dan ayam. Tambah 1 sendok makan kecap asin, 1 sendok teh gula, dan 1 sendok teh cuka. Aduk 2 menit.', textZh: '下黄瓜和鸡肉，加1饭勺生抽、1茶勺糖、1茶勺醋，炒2分钟。' },
      { emoji: '🥜', textId: 'Masukkan {peanut}. Aduk 1 menit. Matikan api. Angkat.', textZh: '下1把花生，炒1分钟，关火出锅。' },
    ],
    tipId: 'Jangan masak ayam terlalu lama supaya tetap empuk.',
    tipZh: '鸡肉不要炒太久，保持嫩滑。',
  },
  {
    id: 'laver-egg-soup',
    nameZh: '紫菜蛋花汤',
    nameId: 'Sup Telur Rumput Laut',
    emoji: '🍲',
    category: 'soup',
    timeMin: 10,
    difficulty: 1,
    ingredients: [
      { key: 'laver',    qty: 2 },
      { key: 'egg',      qty: 2 },
      { key: 'scallion', qty: 1 },
    ],
    steps: [
      { emoji: '💧', textId: 'Tuang 3 mangkuk air ke panci. Masak dengan api besar sampai mendidih.', textZh: '锅里倒3碗水，大火烧开。' },
      { emoji: '🥚', textId: 'Sambil menunggu, kocok {egg} di mangkuk dengan garpu.', textZh: '等待时把2个鸡蛋在碗里用叉子打散。' },
      { emoji: '🍙', textId: 'Sobek {laver} kecil-kecil dengan tangan. Masukkan ke air mendidih. Masak 1 menit.', textZh: '2张紫菜用手撕成小块，放入沸水中煮1分钟。' },
      { emoji: '🌀', textId: 'Tuang telur pelan-pelan sambil aduk air dengan sendok. Telur akan jadi seperti benang.', textZh: '慢慢倒入蛋液，同时用勺子搅水，蛋花会成丝状。' },
      { emoji: '🧂', textId: 'Tambah 1 sendok teh garam dan sedikit merica. Aduk. Matikan api.', textZh: '加1茶勺盐和少许胡椒，搅匀，关火。' },
      { emoji: '🍽️', textId: 'Taburi {scallion} yang sudah dipotong kecil. Sajikan panas.', textZh: '撒上切好的葱花（1根），趁热上桌。' },
    ],
    tipId: 'Tuang telur pelan-pelan supaya hasilnya tipis dan lembut, bukan menggumpal.',
    tipZh: '蛋液要慢慢倒，蛋花才细滑，不会结块。',
  },
  {
    id: 'mapo-tofu',
    nameZh: '麻婆豆腐（简化版）',
    nameId: 'Tahu Mapo',
    emoji: '🌶️',
    category: 'tofu',
    timeMin: 15,
    difficulty: 1,
    ingredients: [
      { key: 'tofu',        qty: 4 },
      { key: 'minced_pork', qty: 1 },
      { key: 'garlic',      qty: 3 },
      { key: 'chili',       qty: 1 },
      { key: 'scallion',    qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Potong {tofu} sebesar dadu.', textZh: '4块豆腐切成小丁。' },
      { emoji: '🧄', textId: 'Geprek {garlic}, lalu potong kecil-kecil. Potong {chili} tipis-tipis.', textZh: '3瓣蒜拍碎切小，1个辣椒切细丝。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 1 sendok makan minyak. Masukkan bawang putih, cabai, dan {minced_pork}. Aduk 2 menit dengan api sedang sampai daging berubah warna.', textZh: '烧热锅倒1饭勺油，下蒜、辣椒和1碗猪肉末，中火炒2分钟至变色。' },
      { emoji: '🥘', textId: 'Masukkan tahu. Tuang 1 mangkuk air, 2 sendok makan kecap manis, dan 1 sendok makan kecap asin. Aduk pelan supaya tahu tidak hancur.', textZh: '下豆腐，倒1碗水、2饭勺甜酱油、1饭勺生抽，轻轻翻动别把豆腐弄碎。' },
      { emoji: '⏲️', textId: 'Masak 5 menit dengan api kecil sampai air tinggal sedikit.', textZh: '小火煮5分钟，至汤汁变少。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Taburi {scallion} yang sudah dipotong kecil. Sajikan.', textZh: '关火出锅，撒上切好的葱花（1根），上桌。' },
    ],
    tipId: 'Kalau tidak suka pedas, cabai boleh tidak dipakai.',
    tipZh: '不吃辣的话，辣椒可以不放。',
  },
  {
    id: 'pepper-pork-strips',
    nameZh: '青椒肉丝',
    nameId: 'Tumis Daging Babi dan Paprika',
    emoji: '🫑',
    category: 'pork',
    timeMin: 20,
    difficulty: 1,
    ingredients: [
      { key: 'pork',        qty: 2 },
      { key: 'bell_pepper', qty: 2 },
      { key: 'garlic',      qty: 2 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Potong {pork} tipis-tipis memanjang, seperti korek api.', textZh: '2块猪肉切成细丝（像火柴棍）。' },
      { emoji: '🧂', textId: 'Taruh daging di mangkuk. Tambah 1 sendok makan kecap asin dan 1 sendok makan tepung maizena. Aduk rata. Diamkan 10 menit.', textZh: '肉丝放碗里，加1饭勺生抽和1饭勺淀粉，拌匀，腌10分钟。' },
      { emoji: '🫑', textId: 'Potong {bell_pepper} memanjang. Geprek dan potong kecil {garlic}.', textZh: '2个青椒切丝，2瓣蒜拍碎切小。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan daging. Masak 3 menit dengan api besar sampai berubah warna. Angkat ke piring.', textZh: '烧热锅倒2饭勺油，下肉丝大火炒3分钟至变色，盛出。' },
      { emoji: '🧄', textId: 'Tuang 1 sendok makan minyak. Masukkan bawang putih. Aduk 30 detik.', textZh: '倒1饭勺油，下蒜炒30秒。' },
      { emoji: '🫑', textId: 'Masukkan paprika. Masak 2 menit dengan api besar.', textZh: '下青椒，大火炒2分钟。' },
      { emoji: '🍽️', textId: 'Masukkan daging kembali. Tambah setengah sendok teh garam. Aduk 1 menit. Matikan api. Sajikan.', textZh: '倒回肉丝，加半茶勺盐，炒1分钟，关火出锅。' },
    ],
    tipId: 'Masak paprika dengan api besar supaya tetap renyah.',
    tipZh: '青椒大火快炒，保持脆嫩。',
  },
  {
    id: 'potato-chicken-stew',
    nameZh: '土豆炖鸡',
    nameId: 'Ayam Rebus Kentang',
    emoji: '🥔',
    category: 'chicken',
    timeMin: 35,
    difficulty: 1,
    ingredients: [
      { key: 'chicken_leg', qty: 2 },
      { key: 'potato',      qty: 2 },
      { key: 'carrot',      qty: 1 },
      { key: 'ginger',      qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Potong {chicken_leg} jadi 3 bagian tiap potong.', textZh: '2个鸡腿每块切成3块。' },
      { emoji: '🥔', textId: 'Kupas {potato} dan {carrot}. Potong sebesar dadu.', textZh: '2个土豆和1根胡萝卜去皮，切成丁。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 1 sendok makan minyak. Masukkan {ginger} yang sudah diiris dan ayam. Masak 3 menit dengan api sedang.', textZh: '烧热锅倒1饭勺油，下姜片（1块姜切片）和鸡肉，中火炒3分钟。' },
      { emoji: '💧', textId: 'Tuang 3 mangkuk air dan 2 sendok makan kecap asin. Masak sampai mendidih.', textZh: '倒3碗水和2饭勺生抽，煮开。' },
      { emoji: '⏲️', textId: 'Kecilkan api. Tutup wajan. Masak 15 menit.', textZh: '转小火，盖锅盖，煮15分钟。' },
      { emoji: '🥔', textId: 'Masukkan kentang dan wortel. Tutup lagi. Masak 10 menit dengan api kecil sampai kentang lembek.', textZh: '下土豆和胡萝卜，再盖锅盖，小火煮10分钟至土豆软烂。' },
      { emoji: '🍽️', textId: 'Tambah setengah sendok teh garam. Aduk. Matikan api. Sajikan.', textZh: '加半茶勺盐，搅匀，关火出锅。' },
    ],
    tipId: 'Tusuk kentang dengan garpu. Kalau mudah tembus, berarti sudah matang.',
    tipZh: '用叉子戳土豆，轻松穿透就是熟了。',
  },
  {
    id: 'cola-chicken-wings',
    nameZh: '可乐鸡翅',
    nameId: 'Sayap Ayam Cola',
    emoji: '🥤',
    category: 'chicken',
    timeMin: 25,
    difficulty: 1,
    ingredients: [
      { key: 'chicken_wing', qty: 8 },
      { key: 'cola',         qty: 1 },
      { key: 'ginger',       qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cuci {chicken_wing}. Sayat 2 kali tiap sayap supaya bumbu masuk.', textZh: '8个鸡翅洗净，每个划2刀方便入味。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 1 sendok makan minyak. Masukkan sayap dan {ginger} yang sudah diiris.', textZh: '烧热锅倒1饭勺油，下鸡翅和姜片（1块姜切片）。' },
      { emoji: '🍗', textId: 'Masak 3 menit dengan api sedang. Balik sayap supaya kedua sisi berubah warna.', textZh: '中火煎3分钟，翻面让两面都变色。' },
      { emoji: '🥤', textId: 'Tuang {cola} dan 1 sendok makan kecap asin. Masak sampai mendidih.', textZh: '倒1罐可乐和1饭勺生抽，煮开。' },
      { emoji: '⏲️', textId: 'Kecilkan api. Tutup wajan. Masak 10 menit.', textZh: '转小火，盖锅盖，煮10分钟。' },
      { emoji: '🔥', textId: 'Buka tutup. Besarkan api. Masak 3 menit sampai kuah kental dan menempel di sayap.', textZh: '开盖转大火，煮3分钟至汤汁浓稠裹住鸡翅。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan.', textZh: '关火，盛出上桌。' },
    ],
    tipId: 'Pakai cola biasa, bukan cola tanpa gula, supaya hasilnya manis dan mengkilap.',
    tipZh: '用普通可乐，不要用无糖可乐，做出来才甜亮。',
  },
  {
    id: 'garlic-broccoli',
    nameZh: '蒜蓉西兰花',
    nameId: 'Brokoli Bawang Putih',
    emoji: '🥦',
    category: 'veg',
    timeMin: 15,
    difficulty: 1,
    ingredients: [
      { key: 'broccoli', qty: 1 },
      { key: 'garlic',   qty: 4 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cuci {broccoli}. Potong jadi kuntum-kuntum kecil.', textZh: '1个西兰花洗净，切成小朵。' },
      { emoji: '💧', textId: 'Tuang 3 mangkuk air ke panci. Masak dengan api besar sampai mendidih.', textZh: '锅里倒3碗水，大火烧开。' },
      { emoji: '🥦', textId: 'Masukkan brokoli. Masak 2 menit. Angkat dan tiriskan.', textZh: '下西兰花煮2分钟，捞出沥干。' },
      { emoji: '🧄', textId: 'Geprek {garlic}, lalu potong kecil-kecil.', textZh: '4瓣蒜拍碎切小。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan bawang putih. Aduk 30 detik dengan api sedang sampai wangi.', textZh: '烧热锅倒2饭勺油，下蒜末中火炒30秒至香。' },
      { emoji: '🥦', textId: 'Masukkan brokoli. Tambah 1 sendok makan saus tiram dan sedikit garam. Aduk 2 menit dengan api besar.', textZh: '下西兰花，加1饭勺蚝油和少许盐，大火炒2分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan.', textZh: '关火出锅上桌。' },
    ],
    tipId: 'Jangan rebus brokoli terlalu lama supaya warnanya tetap hijau.',
    tipZh: '西兰花别煮太久，颜色才翠绿。',
  },
  {
    id: 'sour-spicy-potato',
    nameZh: '酸辣土豆丝',
    nameId: 'Kentang Asam Pedas',
    emoji: '🌶️',
    category: 'veg',
    timeMin: 15,
    difficulty: 1,
    ingredients: [
      { key: 'potato', qty: 2 },
      { key: 'chili',  qty: 2 },
      { key: 'garlic', qty: 2 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Kupas {potato}. Potong tipis-tipis memanjang, seperti korek api.', textZh: '2个土豆去皮，切成细丝（像火柴棍）。' },
      { emoji: '💧', textId: 'Rendam kentang di semangkuk air selama 5 menit supaya tidak lengket. Tiriskan.', textZh: '土豆丝泡在一碗水里5分钟防粘，沥干。' },
      { emoji: '🧄', textId: 'Geprek {garlic}, potong kecil. Potong {chili} tipis-tipis.', textZh: '2瓣蒜拍碎切小，2个辣椒切细丝。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan bawang putih dan cabai. Aduk 30 detik dengan api besar.', textZh: '烧热锅倒2饭勺油，下蒜和辣椒大火炒30秒。' },
      { emoji: '🥔', textId: 'Masukkan kentang. Aduk 2 menit dengan api besar.', textZh: '下土豆丝，大火翻炒2分钟。' },
      { emoji: '🧂', textId: 'Tambah 1 sendok makan kecap asin, 1 sendok makan cuka, dan sedikit garam. Aduk 1 menit.', textZh: '加1饭勺生抽、1饭勺醋和少许盐，翻炒1分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan.', textZh: '关火出锅上桌。' },
    ],
    tipId: 'Masukkan cuka di akhir supaya rasanya tetap segar.',
    tipZh: '醋最后放，味道才清爽。',
  },
  {
    id: 'braised-pork',
    nameZh: '红烧肉（简化版）',
    nameId: 'Babi Kecap Merah',
    emoji: '🍖',
    category: 'pork',
    timeMin: 45,
    difficulty: 2,
    ingredients: [
      { key: 'pork',   qty: 4 },
      { key: 'ginger', qty: 2 },
      { key: 'garlic', qty: 3 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Potong {pork} sebesar dadu besar, kira-kira 3 senti.', textZh: '4块猪肉切成大丁，约3厘米。' },
      { emoji: '💧', textId: 'Rebus 4 mangkuk air di panci. Masukkan daging. Masak 2 menit. Angkat, buang airnya.', textZh: '锅里煮4碗水，下猪肉煮2分钟，捞出倒掉水。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 1 sendok makan minyak. Masukkan {ginger} yang sudah diiris dan {garlic} yang sudah digeprek. Aduk 30 detik.', textZh: '烧热锅倒1饭勺油，下姜片（2块姜切片）和拍碎的蒜（3瓣），炒30秒。' },
      { emoji: '🥘', textId: 'Masukkan daging. Tambah 2 sendok makan kecap manis, 1 sendok makan kecap asin, dan 2 mangkuk air.', textZh: '下猪肉，加2饭勺甜酱油、1饭勺生抽和2碗水。' },
      { emoji: '⏲️', textId: 'Masak sampai mendidih. Kecilkan api. Tutup wajan. Masak 30 menit.', textZh: '煮开后转小火，盖锅盖煮30分钟。' },
      { emoji: '🔥', textId: 'Buka tutup. Besarkan api. Masak 3 menit sampai kuah kental.', textZh: '开盖转大火，煮3分钟至汤汁浓稠。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan.', textZh: '关火出锅上桌。' },
    ],
    tipId: 'Kecap manis membuat warna daging cokelat mengkilap tanpa perlu karamel.',
    tipZh: '甜酱油能让肉色红亮，不用炒糖色。',
  },
  {
    id: 'steamed-fish',
    nameZh: '清蒸鱼',
    nameId: 'Ikan Kukus Jahe',
    emoji: '🐟',
    category: 'fish',
    timeMin: 20,
    difficulty: 1,
    ingredients: [
      { key: 'fish',     qty: 1 },
      { key: 'ginger',   qty: 2 },
      { key: 'scallion', qty: 2 },
    ],
    steps: [
      { emoji: '🐟', textId: 'Cuci {fish} sampai bersih. Letakkan di piring tahan panas.', textZh: '1条鱼洗净，放在耐热盘子上。' },
      { emoji: '🔪', textId: 'Iris tipis {ginger}. Taruh setengah di bawah ikan dan setengah di atas ikan.', textZh: '2块姜切薄片，一半垫鱼下，一半铺鱼上。' },
      { emoji: '💧', textId: 'Tuang 3 mangkuk air ke panci kukus. Masak dengan api besar sampai mendidih.', textZh: '蒸锅倒3碗水，大火烧开。' },
      { emoji: '♨️', textId: 'Masukkan piring berisi ikan. Kukus 8 menit dengan api besar.', textZh: '放入鱼盘，大火蒸8分钟。' },
      { emoji: '💦', textId: 'Angkat piring. Buang air di piring supaya tidak amis.', textZh: '取出盘子，倒掉盘中水，去腥。' },
      { emoji: '🥢', textId: 'Siram ikan dengan 2 sendok makan kecap asin. Taburi {scallion} yang sudah dipotong kecil.', textZh: '鱼上淋2饭勺生抽，撒上切好的葱花（2根）。' },
      { emoji: '🔥', textId: 'Panaskan 2 sendok makan minyak di wajan sampai panas. Siram di atas ikan.', textZh: '锅里烧热2饭勺油，浇在鱼上。' },
      { emoji: '🍽️', textId: 'Sajikan segera selagi panas.', textZh: '趁热立即上桌。' },
    ],
    tipId: 'Jangan kukus lebih dari 10 menit supaya daging ikan tidak keras.',
    tipZh: '蒸不要超过10分钟，鱼肉才不会老。',
  },
  {
    id: 'boiled-shrimp',
    nameZh: '白灼虾',
    nameId: 'Udang Rebus',
    emoji: '🦐',
    category: 'shrimp',
    timeMin: 10,
    difficulty: 1,
    ingredients: [
      { key: 'shrimp',   qty: 10 },
      { key: 'ginger',   qty: 1 },
      { key: 'scallion', qty: 1 },
    ],
    steps: [
      { emoji: '🦐', textId: 'Cuci {shrimp} sampai bersih.', textZh: '10只虾洗净。' },
      { emoji: '💧', textId: 'Tuang 4 mangkuk air ke panci. Masukkan {ginger} yang sudah diiris dan {scallion}.', textZh: '锅里倒4碗水，放入姜片（1块姜切片）和1根葱。' },
      { emoji: '🔥', textId: 'Masak dengan api besar sampai mendidih.', textZh: '大火烧开。' },
      { emoji: '🦐', textId: 'Masukkan udang. Masak 2 menit sampai semua udang berwarna merah.', textZh: '下虾煮2分钟，至全部变红。' },
      { emoji: '🥣', textId: 'Sambil menunggu, buat saus: campur 2 sendok makan kecap asin dan setengah sendok teh gula di mangkuk kecil.', textZh: '等待时调蘸料：小碗里加2饭勺生抽和半茶勺糖，搅匀。' },
      { emoji: '🍽️', textId: 'Angkat udang. Tiriskan. Sajikan dengan saus kecap.', textZh: '捞出虾沥干，配蘸料上桌。' },
    ],
    tipId: 'Udang yang sudah merah dan melengkung tandanya sudah matang. Jangan direbus terlalu lama.',
    tipZh: '虾变红弯曲就是熟了，别煮太久。',
  },
  {
    id: 'onion-beef',
    nameZh: '洋葱炒牛肉',
    nameId: 'Tumis Daging Sapi dan Bawang Bombay',
    emoji: '🧅',
    category: 'beef',
    timeMin: 20,
    difficulty: 1,
    ingredients: [
      { key: 'beef',   qty: 2 },
      { key: 'onion',  qty: 1 },
      { key: 'garlic', qty: 2 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Potong {beef} tipis-tipis.', textZh: '2块牛肉切薄片。' },
      { emoji: '🧂', textId: 'Taruh daging di mangkuk. Tambah 1 sendok makan kecap asin dan 1 sendok makan tepung maizena. Aduk rata. Diamkan 10 menit.', textZh: '牛肉放碗里，加1饭勺生抽和1饭勺淀粉，拌匀，腌10分钟。' },
      { emoji: '🧅', textId: 'Kupas {onion}. Potong memanjang. Geprek dan potong kecil {garlic}.', textZh: '1个洋葱去皮切条，2瓣蒜拍碎切小。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan daging. Masak 2 menit dengan api besar sampai berubah warna. Angkat ke piring.', textZh: '烧热锅倒2饭勺油，下牛肉大火炒2分钟至变色，盛出。' },
      { emoji: '🧅', textId: 'Tuang 1 sendok makan minyak. Masukkan bawang bombay dan bawang putih. Masak 2 menit dengan api sedang sampai layu.', textZh: '倒1饭勺油，下洋葱和蒜，中火炒2分钟至软。' },
      { emoji: '🥩', textId: 'Masukkan daging kembali. Tambah 1 sendok makan kecap manis dan sedikit merica. Aduk 1 menit dengan api besar.', textZh: '倒回牛肉，加1饭勺甜酱油和少许胡椒，大火炒1分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan.', textZh: '关火出锅上桌。' },
    ],
    tipId: 'Daging sapi cepat keras, jadi masak sebentar saja dengan api besar.',
    tipZh: '牛肉容易老，大火快炒就好。',
  },
  {
    id: 'yuxiang-eggplant',
    nameZh: '鱼香茄子（简化版）',
    nameId: 'Terong Asam Manis',
    emoji: '🍆',
    category: 'veg',
    timeMin: 20,
    difficulty: 1,
    ingredients: [
      { key: 'eggplant', qty: 2 },
      { key: 'garlic',   qty: 3 },
      { key: 'chili',    qty: 1 },
      { key: 'scallion', qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cuci {eggplant}. Potong panjang-panjang sebesar jari.', textZh: '2个茄子洗净，切成手指粗的条。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 3 sendok makan minyak. Masukkan terong. Masak 4 menit dengan api sedang sampai lembek. Angkat.', textZh: '烧热锅倒3饭勺油，下茄子中火炒4分钟至软，盛出。' },
      { emoji: '🧄', textId: 'Geprek {garlic}, potong kecil. Potong {chili} tipis-tipis.', textZh: '3瓣蒜拍碎切小，1个辣椒切细丝。' },
      { emoji: '🌶️', textId: 'Tuang 1 sendok makan minyak. Masukkan bawang putih dan cabai. Aduk 30 detik dengan api sedang.', textZh: '倒1饭勺油，下蒜和辣椒中火炒30秒。' },
      { emoji: '🍆', textId: 'Masukkan terong kembali. Tambah 1 sendok makan kecap asin, 1 sendok makan cuka, dan 2 sendok teh gula.', textZh: '倒回茄子，加1饭勺生抽、1饭勺醋和2茶勺糖。' },
      { emoji: '🥘', textId: 'Tuang setengah mangkuk air. Aduk pelan. Masak 2 menit sampai kuah kental.', textZh: '倒半碗水，轻轻翻动，煮2分钟至汤汁浓稠。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Taburi {scallion} yang sudah dipotong kecil. Sajikan.', textZh: '关火出锅，撒上切好的葱花（1根），上桌。' },
    ],
    tipId: 'Terong menyerap banyak minyak, jadi jangan kaget kalau minyak cepat habis.',
    tipZh: '茄子很吸油，油很快没了别惊讶。',
  },
  {
    id: 'egg-fried-rice',
    nameZh: '鸡蛋炒饭',
    nameId: 'Nasi Goreng Telur',
    emoji: '🍳',
    category: 'egg',
    timeMin: 15,
    difficulty: 1,
    ingredients: [
      { key: 'rice',     qty: 2 },
      { key: 'egg',      qty: 2 },
      { key: 'carrot',   qty: 1 },
      { key: 'scallion', qty: 1 },
    ],
    steps: [
      { emoji: '🥚', textId: 'Pecahkan {egg} ke dalam mangkuk. Kocok dengan garpu selama 30 detik.', textZh: '2个鸡蛋打入碗里，用叉子搅30秒。' },
      { emoji: '🥕', textId: 'Kupas {carrot}. Potong kecil-kecil sebesar kacang.', textZh: '1根胡萝卜去皮，切成黄豆大的小丁。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan telur. Aduk sampai matang. Angkat.', textZh: '烧热锅倒2饭勺油，下蛋液炒熟，盛出。' },
      { emoji: '🥕', textId: 'Tuang 1 sendok makan minyak. Masukkan wortel. Masak 1 menit dengan api besar.', textZh: '倒1饭勺油，下胡萝卜丁大火炒1分钟。' },
      { emoji: '🍚', textId: 'Masukkan {rice}. Tekan-tekan dengan sendok supaya tidak menggumpal. Aduk 2 menit dengan api besar.', textZh: '下2碗米饭，用铲子压散不结块，大火翻炒2分钟。' },
      { emoji: '🧂', textId: 'Masukkan telur kembali. Tambah 1 sendok makan kecap asin dan setengah sendok teh garam. Aduk 1 menit.', textZh: '倒回鸡蛋，加1饭勺生抽和半茶勺盐，翻炒1分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Taburi {scallion} yang sudah dipotong kecil. Sajikan.', textZh: '关火，撒上切好的葱花（1根），上桌。' },
    ],
    tipId: 'Nasi sisa kemarin dari kulkas lebih enak untuk nasi goreng, tidak lengket.',
    tipZh: '冰箱里的隔夜饭做炒饭更香，不粘。',
  },
  {
    id: 'tomato-egg-noodle',
    nameZh: '西红柿鸡蛋面',
    nameId: 'Mie Kuah Tomat Telur',
    emoji: '🍜',
    category: 'egg',
    timeMin: 20,
    difficulty: 1,
    ingredients: [
      { key: 'noodles',  qty: 2 },
      { key: 'tomato',   qty: 1 },
      { key: 'egg',      qty: 2 },
      { key: 'scallion', qty: 1 },
    ],
    steps: [
      { emoji: '🍅', textId: 'Cuci {tomato}. Potong kecil-kecil.', textZh: '1个番茄洗净切小块。' },
      { emoji: '🥚', textId: 'Pecahkan {egg} ke dalam mangkuk. Kocok dengan garpu.', textZh: '2个鸡蛋打入碗里，用叉子打散。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 1 sendok makan minyak. Masukkan telur. Aduk sampai matang. Angkat.', textZh: '烧热锅倒1饭勺油，下蛋液炒熟，盛出。' },
      { emoji: '🍅', textId: 'Masukkan tomat. Masak 2 menit dengan api sedang sampai lembek.', textZh: '下番茄，中火炒2分钟至软烂。' },
      { emoji: '💧', textId: 'Tuang 4 mangkuk air. Masak dengan api besar sampai mendidih.', textZh: '倒4碗水，大火烧开。' },
      { emoji: '🍜', textId: 'Masukkan {noodles}. Masak 3 menit dengan api sedang. Aduk sesekali supaya tidak menempel.', textZh: '下2个面饼，中火煮3分钟，偶尔搅动防粘。' },
      { emoji: '🧂', textId: 'Masukkan telur kembali. Tambah 1 sendok teh garam. Aduk. Matikan api.', textZh: '倒回鸡蛋，加1茶勺盐，搅匀，关火。' },
      { emoji: '🍽️', textId: 'Tuang ke mangkuk besar. Taburi {scallion} yang sudah dipotong kecil. Sajikan panas.', textZh: '倒入大碗，撒上切好的葱花（1根），趁热上桌。' },
    ],
    tipId: 'Kalau suka kuah lebih kental, masak tomat lebih lama sampai hancur.',
    tipZh: '喜欢汤浓一点，番茄多炒一会儿炒烂。',
  },
  {
    id: 'winter-melon-ribs-soup',
    nameZh: '冬瓜排骨汤',
    nameId: 'Sup Iga dan Bligo',
    emoji: '🍲',
    category: 'soup',
    timeMin: 50,
    difficulty: 1,
    ingredients: [
      { key: 'winter_melon', qty: 4 },
      { key: 'pork_ribs',    qty: 4 },
      { key: 'ginger',       qty: 2 },
    ],
    steps: [
      { emoji: '💧', textId: 'Rebus 4 mangkuk air di panci. Masukkan {pork_ribs}. Masak 3 menit. Angkat dan cuci iga dengan air bersih.', textZh: '锅里煮4碗水，下4块排骨煮3分钟，捞出用清水洗净。' },
      { emoji: '🫚', textId: 'Iris {ginger}.', textZh: '2块姜切片。' },
      { emoji: '💧', textId: 'Tuang 6 mangkuk air bersih ke panci. Masukkan iga dan jahe. Masak dengan api besar sampai mendidih.', textZh: '锅里倒6碗清水，下排骨和姜片，大火烧开。' },
      { emoji: '⏲️', textId: 'Kecilkan api. Tutup panci. Masak 30 menit.', textZh: '转小火，盖锅盖煮30分钟。' },
      { emoji: '🍈', textId: 'Sambil menunggu, kupas {winter_melon}. Potong sebesar dadu besar.', textZh: '等待时把4块冬瓜去皮，切成大块。' },
      { emoji: '🍈', textId: 'Masukkan bligo ke panci. Masak 10 menit dengan api kecil sampai bligo bening dan lembek.', textZh: '冬瓜下锅，小火煮10分钟至透明软烂。' },
      { emoji: '🧂', textId: 'Tambah 1 sendok teh garam. Aduk. Matikan api.', textZh: '加1茶勺盐，搅匀，关火。' },
      { emoji: '🍽️', textId: 'Sajikan panas di mangkuk besar.', textZh: '盛入大碗，趁热上桌。' },
    ],
    tipId: 'Merebus iga dulu membuat kuah bening dan tidak berbau.',
    tipZh: '排骨先焯一遍，汤才清不腥。',
  },
  {
    id: 'corn-ribs-soup',
    nameZh: '玉米排骨汤',
    nameId: 'Sup Iga Jagung',
    emoji: '🌽',
    category: 'soup',
    timeMin: 50,
    difficulty: 1,
    ingredients: [
      { key: 'corn',      qty: 1 },
      { key: 'pork_ribs', qty: 4 },
      { key: 'carrot',    qty: 1 },
      { key: 'ginger',    qty: 1 },
    ],
    steps: [
      { emoji: '💧', textId: 'Rebus 4 mangkuk air di panci. Masukkan {pork_ribs}. Masak 3 menit. Angkat dan cuci iga dengan air bersih.', textZh: '锅里煮4碗水，下4块排骨煮3分钟，捞出用清水洗净。' },
      { emoji: '🌽', textId: 'Potong {corn} jadi 4 bagian. Kupas {carrot}, potong sebesar dadu. Iris {ginger}.', textZh: '1根玉米切成4段；1根胡萝卜去皮切丁；1块姜切片。' },
      { emoji: '💧', textId: 'Tuang 6 mangkuk air bersih ke panci. Masukkan iga dan jahe. Masak dengan api besar sampai mendidih.', textZh: '锅里倒6碗清水，下排骨和姜片，大火烧开。' },
      { emoji: '⏲️', textId: 'Kecilkan api. Tutup panci. Masak 30 menit.', textZh: '转小火，盖锅盖煮30分钟。' },
      { emoji: '🌽', textId: 'Masukkan jagung dan wortel. Tutup lagi. Masak 15 menit dengan api kecil.', textZh: '下玉米和胡萝卜，再盖锅盖，小火煮15分钟。' },
      { emoji: '🧂', textId: 'Tambah 1 sendok teh garam. Aduk. Matikan api.', textZh: '加1茶勺盐，搅匀，关火。' },
      { emoji: '🍽️', textId: 'Sajikan panas di mangkuk besar.', textZh: '盛入大碗，趁热上桌。' },
    ],
    tipId: 'Jagung manis membuat kuah terasa manis alami, tidak perlu tambah gula.',
    tipZh: '甜玉米让汤有天然甜味，不用加糖。',
  },
  {
    id: 'mushroom-greens',
    nameZh: '香菇青菜',
    nameId: 'Tumis Sawi dan Jamur',
    emoji: '🍄',
    category: 'veg',
    timeMin: 15,
    difficulty: 1,
    ingredients: [
      { key: 'greens',   qty: 1 },
      { key: 'mushroom', qty: 5 },
      { key: 'garlic',   qty: 2 },
    ],
    steps: [
      { emoji: '🥬', textId: 'Cuci {greens}. Potong jadi 2 bagian tiap batang.', textZh: '1把青菜洗净，每根切成2段。' },
      { emoji: '🍄', textId: 'Cuci {mushroom}. Potong jadi 2 bagian tiap jamur.', textZh: '5个香菇洗净，每个切成2半。' },
      { emoji: '🧄', textId: 'Geprek {garlic}, lalu potong kecil-kecil.', textZh: '2瓣蒜拍碎切小。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan bawang putih. Aduk 30 detik dengan api sedang sampai wangi.', textZh: '烧热锅倒2饭勺油，下蒜末中火炒30秒至香。' },
      { emoji: '🍄', textId: 'Masukkan jamur. Masak 2 menit dengan api sedang sampai layu.', textZh: '下香菇，中火炒2分钟至软。' },
      { emoji: '🥬', textId: 'Masukkan sawi. Tambah 1 sendok makan saus tiram dan sedikit garam. Aduk 2 menit dengan api besar sampai sawi layu.', textZh: '下青菜，加1饭勺蚝油和少许盐，大火炒2分钟至菜叶变软。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan.', textZh: '关火出锅上桌。' },
    ],
    tipId: 'Masukkan sawi terakhir supaya tidak terlalu lembek.',
    tipZh: '青菜最后放，才不会太烂。',
  },
  {
    id: 'dry-fried-beans',
    nameZh: '干煸四季豆（简化版）',
    nameId: 'Buncis Goreng Kering',
    emoji: '🫛',
    category: 'veg',
    timeMin: 20,
    difficulty: 1,
    ingredients: [
      { key: 'green_beans', qty: 15 },
      { key: 'garlic',      qty: 3 },
      { key: 'chili',       qty: 2 },
    ],
    steps: [
      { emoji: '🫛', textId: 'Cuci {green_beans}. Buang ujungnya. Potong jadi 2 bagian tiap batang. Keringkan dengan kain bersih.', textZh: '15根四季豆洗净去两头，每根掰成2段，用干净布擦干。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 3 sendok makan minyak. Masukkan buncis.', textZh: '烧热锅倒3饭勺油，下四季豆。' },
      { emoji: '🫛', textId: 'Masak 6 menit dengan api sedang. Aduk sesekali sampai kulit buncis keriput. Angkat.', textZh: '中火煎6分钟，偶尔翻动，至表皮起皱，盛出。' },
      { emoji: '🧄', textId: 'Geprek {garlic}, potong kecil. Potong {chili} tipis-tipis.', textZh: '3瓣蒜拍碎切小，2个辣椒切细丝。' },
      { emoji: '🌶️', textId: 'Sisakan 1 sendok makan minyak di wajan. Masukkan bawang putih dan cabai. Aduk 30 detik.', textZh: '锅里留1饭勺油，下蒜和辣椒炒30秒。' },
      { emoji: '🧂', textId: 'Masukkan buncis kembali. Tambah setengah sendok teh garam dan 1 sendok makan kecap asin. Aduk 1 menit.', textZh: '倒回四季豆，加半茶勺盐和1饭勺生抽，翻炒1分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan.', textZh: '关火出锅上桌。' },
    ],
    tipId: 'Buncis harus benar-benar matang. Buncis mentah tidak baik untuk perut.',
    tipZh: '四季豆必须彻底做熟，生的吃了拉肚子。',
  },
  {
    id: 'cucumber-egg',
    nameZh: '黄瓜炒蛋',
    nameId: 'Telur Orak-arik Timun',
    emoji: '🥒',
    category: 'egg',
    timeMin: 10,
    difficulty: 1,
    ingredients: [
      { key: 'cucumber', qty: 1 },
      { key: 'egg',      qty: 3 },
      { key: 'garlic',   qty: 1 },
    ],
    steps: [
      { emoji: '🥒', textId: 'Cuci {cucumber}. Potong tipis-tipis.', textZh: '1根黄瓜洗净切薄片。' },
      { emoji: '🥚', textId: 'Pecahkan {egg} ke dalam mangkuk. Tambah sedikit garam. Kocok dengan garpu selama 30 detik.', textZh: '3个鸡蛋打入碗里，加一点盐，用叉子搅30秒。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan telur. Aduk sampai matang. Angkat ke piring.', textZh: '烧热锅倒2饭勺油，下蛋液炒熟，盛出。' },
      { emoji: '🧄', textId: 'Geprek {garlic}. Tuang 1 sendok makan minyak ke wajan. Masukkan bawang putih. Aduk 30 detik.', textZh: '1瓣蒜拍碎。锅里倒1饭勺油，下蒜炒30秒。' },
      { emoji: '🥒', textId: 'Masukkan timun. Masak 1 menit dengan api besar.', textZh: '下黄瓜片，大火炒1分钟。' },
      { emoji: '🍳', textId: 'Masukkan telur kembali. Tambah setengah sendok teh garam. Aduk 1 menit.', textZh: '倒回鸡蛋，加半茶勺盐，翻炒1分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan.', textZh: '关火出锅上桌。' },
    ],
    tipId: 'Timun cepat matang, jadi masak sebentar saja supaya tetap renyah.',
    tipZh: '黄瓜熟得快，稍炒一下保持脆口。',
  },
  {
    id: 'pumpkin-soup',
    nameZh: '南瓜汤',
    nameId: 'Sup Labu',
    emoji: '🎃',
    category: 'soup',
    timeMin: 25,
    difficulty: 1,
    ingredients: [
      { key: 'pumpkin', qty: 4 },
      { key: 'garlic',  qty: 1 },
    ],
    steps: [
      { emoji: '🎃', textId: 'Kupas {pumpkin}. Buang bijinya. Potong sebesar dadu.', textZh: '4块南瓜去皮去籽，切成丁。' },
      { emoji: '🧄', textId: 'Geprek {garlic}, lalu potong kecil-kecil.', textZh: '1瓣蒜拍碎切小。' },
      { emoji: '🔥', textId: 'Panaskan panci. Tuang 1 sendok makan minyak. Masukkan bawang putih. Aduk 30 detik dengan api sedang.', textZh: '烧热锅倒1饭勺油，下蒜末中火炒30秒。' },
      { emoji: '🎃', textId: 'Masukkan labu. Aduk 2 menit.', textZh: '下南瓜，翻炒2分钟。' },
      { emoji: '💧', textId: 'Tuang 3 mangkuk air. Masak dengan api besar sampai mendidih.', textZh: '倒3碗水，大火烧开。' },
      { emoji: '⏲️', textId: 'Kecilkan api. Tutup panci. Masak 15 menit sampai labu lembek.', textZh: '转小火，盖锅盖煮15分钟至南瓜软烂。' },
      { emoji: '🥄', textId: 'Tekan-tekan labu dengan sendok sampai hancur. Tambah setengah sendok teh garam dan 1 sendok teh gula. Aduk. Matikan api.', textZh: '用勺子把南瓜压碎，加半茶勺盐和1茶勺糖，搅匀，关火。' },
      { emoji: '🍽️', textId: 'Sajikan panas di mangkuk.', textZh: '盛碗，趁热上桌。' },
    ],
    tipId: 'Kalau suka sup lebih halus, hancurkan labu lebih lama dengan sendok.',
    tipZh: '喜欢更细腻的汤，南瓜多压一会儿。',
  },
  {
    id: 'minced-pork-tofu',
    nameZh: '肉末豆腐',
    nameId: 'Tahu Daging Cincang',
    emoji: '🥘',
    category: 'tofu',
    timeMin: 15,
    difficulty: 1,
    ingredients: [
      { key: 'tofu',        qty: 4 },
      { key: 'minced_pork', qty: 1 },
      { key: 'garlic',      qty: 2 },
      { key: 'scallion',    qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Potong {tofu} sebesar dadu.', textZh: '4块豆腐切成小丁。' },
      { emoji: '🧄', textId: 'Geprek {garlic}, lalu potong kecil-kecil.', textZh: '2瓣蒜拍碎切小。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 1 sendok makan minyak. Masukkan bawang putih dan {minced_pork}. Aduk 2 menit dengan api sedang sampai daging berubah warna.', textZh: '烧热锅倒1饭勺油，下蒜和1碗猪肉末，中火炒2分钟至变色。' },
      { emoji: '🥘', textId: 'Masukkan tahu. Tuang 1 mangkuk air, 2 sendok makan kecap manis, dan 1 sendok makan kecap asin. Aduk pelan supaya tahu tidak hancur.', textZh: '下豆腐，倒1碗水、2饭勺甜酱油、1饭勺生抽，轻轻翻动别把豆腐弄碎。' },
      { emoji: '⏲️', textId: 'Masak 5 menit dengan api kecil sampai air tinggal sedikit.', textZh: '小火煮5分钟，至汤汁变少。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Taburi {scallion} yang sudah dipotong kecil. Sajikan.', textZh: '关火出锅，撒上切好的葱花（1根），上桌。' },
    ],
    tipId: 'Aduk pelan-pelan saja supaya tahu tetap utuh dan cantik.',
    tipZh: '轻轻翻动就好，豆腐才完整好看。',
  },
  {
    id: 'garlic-steamed-shrimp',
    nameZh: '蒜蓉蒸虾',
    nameId: 'Udang Kukus Bawang Putih',
    emoji: '🧄',
    category: 'shrimp',
    timeMin: 20,
    difficulty: 1,
    ingredients: [
      { key: 'shrimp',   qty: 8 },
      { key: 'garlic',   qty: 5 },
      { key: 'scallion', qty: 1 },
    ],
    steps: [
      { emoji: '🦐', textId: 'Cuci {shrimp}. Potong punggung udang dengan gunting. Buang garis hitamnya.', textZh: '8只虾洗净，用剪刀剪开虾背，去掉黑线。' },
      { emoji: '🧄', textId: 'Geprek {garlic}, lalu potong kecil-kecil.', textZh: '5瓣蒜拍碎切小。' },
      { emoji: '🥣', textId: 'Campur bawang putih, 2 sendok makan minyak, 1 sendok makan kecap asin, dan setengah sendok teh gula di mangkuk.', textZh: '碗里混合蒜末、2饭勺油、1饭勺生抽和半茶勺糖。' },
      { emoji: '🍽️', textId: 'Taruh udang di piring tahan panas. Siram dengan bumbu bawang putih.', textZh: '虾摆在耐热盘子上，淋上蒜蓉料。' },
      { emoji: '💧', textId: 'Tuang 3 mangkuk air ke panci kukus. Masak dengan api besar sampai mendidih.', textZh: '蒸锅倒3碗水，大火烧开。' },
      { emoji: '♨️', textId: 'Masukkan piring berisi udang. Kukus 5 menit dengan api besar sampai udang merah.', textZh: '放入虾盘，大火蒸5分钟至虾变红。' },
      { emoji: '🍽️', textId: 'Angkat. Taburi {scallion} yang sudah dipotong kecil. Sajikan panas.', textZh: '取出，撒上切好的葱花（1根），趁热上桌。' },
    ],
    tipId: 'Jangan kukus terlalu lama, udang jadi keras kalau kelamaan.',
    tipZh: '别蒸太久，虾肉会变硬。',
  },
  {
    id: 'sweet-sour-pork',
    nameZh: '糖醋里脊（简化版）',
    nameId: 'Daging Asam Manis',
    emoji: '🍬',
    category: 'pork',
    timeMin: 25,
    difficulty: 1,
    ingredients: [
      { key: 'pork', qty: 3 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Potong {pork} memanjang, sebesar jari.', textZh: '3块猪肉切成手指粗的条。' },
      { emoji: '🥣', textId: 'Taruh daging di mangkuk. Tambah 3 sendok makan tepung maizena dan 2 sendok makan air. Aduk sampai daging terbalut rata.', textZh: '肉放碗里，加3饭勺淀粉和2饭勺水，拌匀裹上糊。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 5 sendok makan minyak. Masukkan daging satu per satu.', textZh: '烧热锅倒5饭勺油，把肉一条条下锅。' },
      { emoji: '🍖', textId: 'Goreng 5 menit dengan api sedang sampai kuning dan renyah. Angkat. Tiriskan.', textZh: '中火炸5分钟至金黄酥脆，捞出沥油。' },
      { emoji: '🥘', textId: 'Buang minyak dari wajan. Masukkan 2 sendok makan gula, 2 sendok makan cuka, 1 sendok makan kecap asin, dan setengah mangkuk air. Masak 1 menit dengan api sedang sampai kental.', textZh: '倒掉锅里的油，加2饭勺糖、2饭勺醋、1饭勺生抽和半碗水，中火煮1分钟至浓稠。' },
      { emoji: '🍽️', textId: 'Masukkan daging. Aduk cepat sampai semua terbalut saus. Matikan api. Sajikan.', textZh: '下炸好的肉，快速翻匀裹上酱汁，关火出锅。' },
    ],
    tipId: 'Masukkan daging ke saus tepat sebelum makan supaya tetap renyah.',
    tipZh: '肉吃之前再裹酱，才保持酥脆。',
  },
  {
    id: 'hand-torn-cabbage',
    nameZh: '手撕包菜',
    nameId: 'Tumis Kol Sobek',
    emoji: '🥬',
    category: 'veg',
    timeMin: 10,
    difficulty: 1,
    ingredients: [
      { key: 'cabbage', qty: 6 },
      { key: 'garlic',  qty: 3 },
      { key: 'chili',   qty: 2 },
    ],
    steps: [
      { emoji: '🥬', textId: 'Sobek {cabbage} dengan tangan jadi potongan sedang. Cuci bersih. Tiriskan.', textZh: '6片包菜用手撕成中等块，洗净沥干。' },
      { emoji: '🧄', textId: 'Geprek {garlic}, potong kecil. Potong {chili} tipis-tipis.', textZh: '3瓣蒜拍碎切小，2个辣椒切细丝。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan bawang putih dan cabai. Aduk 30 detik dengan api besar.', textZh: '烧热锅倒2饭勺油，下蒜和辣椒大火炒30秒。' },
      { emoji: '🥬', textId: 'Masukkan kol. Aduk 2 menit dengan api besar.', textZh: '下包菜，大火翻炒2分钟。' },
      { emoji: '🧂', textId: 'Tambah 1 sendok makan kecap asin, setengah sendok teh garam, dan 1 sendok teh cuka. Aduk 1 menit.', textZh: '加1饭勺生抽、半茶勺盐和1茶勺醋，翻炒1分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan.', textZh: '关火出锅上桌。' },
    ],
    tipId: 'Pakai api besar dan masak cepat supaya kol tetap renyah.',
    tipZh: '大火快炒，包菜才脆。',
  },
  {
    id: 'chives-egg',
    nameZh: '韭菜炒蛋',
    nameId: 'Telur Orak-arik Kucai',
    emoji: '🌱',
    category: 'egg',
    timeMin: 10,
    difficulty: 1,
    ingredients: [
      { key: 'chives', qty: 1 },
      { key: 'egg',    qty: 3 },
    ],
    steps: [
      { emoji: '🌱', textId: 'Cuci {chives}. Potong sepanjang 3 senti.', textZh: '1把韭菜洗净，切成3厘米长的段。' },
      { emoji: '🥚', textId: 'Pecahkan {egg} ke dalam mangkuk. Tambah sedikit garam. Kocok dengan garpu selama 30 detik.', textZh: '3个鸡蛋打入碗里，加一点盐，用叉子搅30秒。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan telur. Aduk sampai matang. Angkat ke piring.', textZh: '烧热锅倒2饭勺油，下蛋液炒熟，盛出。' },
      { emoji: '🌱', textId: 'Tuang 1 sendok makan minyak. Masukkan kucai. Aduk 1 menit dengan api besar.', textZh: '倒1饭勺油，下韭菜大火炒1分钟。' },
      { emoji: '🍳', textId: 'Masukkan telur kembali. Tambah setengah sendok teh garam. Aduk 1 menit.', textZh: '倒回鸡蛋，加半茶勺盐，翻炒1分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan.', textZh: '关火出锅上桌。' },
    ],
    tipId: 'Kucai cepat layu, jadi masak sebentar saja dengan api besar.',
    tipZh: '韭菜很容易软，大火快炒就好。',
  },
  {
    id: 'potato-beef-stew',
    nameZh: '土豆炖牛肉',
    nameId: 'Daging Sapi Rebus Kentang',
    emoji: '🥩',
    category: 'beef',
    timeMin: 70,
    difficulty: 2,
    ingredients: [
      { key: 'beef',   qty: 3 },
      { key: 'potato', qty: 2 },
      { key: 'carrot', qty: 1 },
      { key: 'ginger', qty: 2 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Potong {beef} sebesar dadu besar.', textZh: '3块牛肉切成大丁。' },
      { emoji: '💧', textId: 'Rebus 4 mangkuk air di panci. Masukkan daging. Masak 3 menit. Angkat, buang airnya.', textZh: '锅里煮4碗水，下牛肉煮3分钟，捞出倒掉水。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 1 sendok makan minyak. Masukkan {ginger} yang sudah diiris dan daging. Masak 3 menit dengan api sedang.', textZh: '烧热锅倒1饭勺油，下姜片（2块姜切片）和牛肉，中火炒3分钟。' },
      { emoji: '💧', textId: 'Tuang 4 mangkuk air, 2 sendok makan kecap asin, dan 1 sendok makan kecap manis. Masak sampai mendidih.', textZh: '倒4碗水、2饭勺生抽和1饭勺甜酱油，煮开。' },
      { emoji: '⏲️', textId: 'Kecilkan api. Tutup wajan. Masak 40 menit sampai daging empuk.', textZh: '转小火，盖锅盖煮40分钟至牛肉软烂。' },
      { emoji: '🥔', textId: 'Kupas {potato} dan {carrot}. Potong sebesar dadu. Masukkan ke wajan. Tutup lagi. Masak 15 menit dengan api kecil.', textZh: '2个土豆和1根胡萝卜去皮切丁，下锅再盖锅盖，小火煮15分钟。' },
      { emoji: '🍽️', textId: 'Tambah setengah sendok teh garam. Aduk. Matikan api. Sajikan.', textZh: '加半茶勺盐，搅匀，关火出锅。' },
    ],
    tipId: 'Kalau daging belum empuk setelah 40 menit, tambah sedikit air panas dan masak lebih lama.',
    tipZh: '40分钟后牛肉还不烂，加点热水再煮一会儿。',
  },
  {
    id: 'garlic-eggplant',
    nameZh: '蒜蓉茄子',
    nameId: 'Terong Kukus Bawang Putih',
    emoji: '🍆',
    category: 'veg',
    timeMin: 20,
    difficulty: 1,
    ingredients: [
      { key: 'eggplant', qty: 2 },
      { key: 'garlic',   qty: 5 },
      { key: 'scallion', qty: 1 },
    ],
    steps: [
      { emoji: '🍆', textId: 'Cuci {eggplant}. Potong jadi 2 memanjang, lalu potong jadi 3 bagian.', textZh: '2个茄子洗净，先对半剖开，再各切3段。' },
      { emoji: '💧', textId: 'Tuang 3 mangkuk air ke panci kukus. Masak dengan api besar sampai mendidih.', textZh: '蒸锅倒3碗水，大火烧开。' },
      { emoji: '♨️', textId: 'Taruh terong di piring tahan panas. Kukus 8 menit dengan api besar sampai lembek.', textZh: '茄子放耐热盘子上，大火蒸8分钟至软。' },
      { emoji: '🧄', textId: 'Sambil menunggu, geprek {garlic}, potong kecil-kecil. Campur dengan 2 sendok makan kecap asin dan 1 sendok teh gula di mangkuk.', textZh: '等待时把5瓣蒜拍碎切小，加2饭勺生抽和1茶勺糖拌匀。' },
      { emoji: '🥘', textId: 'Angkat terong. Siram dengan campuran bawang putih.', textZh: '取出茄子，淋上蒜蓉料。' },
      { emoji: '🔥', textId: 'Panaskan 1 sendok makan minyak di wajan sampai panas. Siram di atas terong.', textZh: '锅里烧热1饭勺油，浇在茄子上。' },
      { emoji: '🍽️', textId: 'Taburi {scallion} yang sudah dipotong kecil. Sajikan.', textZh: '撒上切好的葱花（1根），上桌。' },
    ],
    tipId: 'Tusuk terong dengan garpu. Kalau lembut, berarti sudah matang.',
    tipZh: '用叉子戳茄子，软了就是熟了。',
  },
  {
    id: 'pan-fried-chicken-leg',
    nameZh: '香煎鸡腿',
    nameId: 'Paha Ayam Goreng Wajan',
    emoji: '🍗',
    category: 'chicken',
    timeMin: 30,
    difficulty: 1,
    ingredients: [
      { key: 'chicken_leg', qty: 2 },
      { key: 'garlic',      qty: 3 },
      { key: 'ginger',      qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cuci {chicken_leg}. Sayat 3 kali tiap paha supaya bumbu masuk dan cepat matang.', textZh: '2个鸡腿洗净，每个划3刀，方便入味和快熟。' },
      { emoji: '🧂', textId: 'Taruh ayam di mangkuk. Tambah 2 sendok makan kecap asin dan 1 sendok makan kecap manis. Aduk rata. Diamkan 15 menit.', textZh: '鸡腿放碗里，加2饭勺生抽和1饭勺甜酱油，拌匀腌15分钟。' },
      { emoji: '🧄', textId: 'Geprek {garlic}. Iris {ginger}.', textZh: '3瓣蒜拍碎，1块姜切片。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan bawang putih dan jahe. Aduk 30 detik dengan api sedang.', textZh: '烧热锅倒2饭勺油，下蒜和姜中火炒30秒。' },
      { emoji: '🍗', textId: 'Letakkan ayam di wajan, sisi kulit menghadap ke bawah. Tutup wajan. Masak 6 menit dengan api kecil.', textZh: '鸡腿皮朝下放入锅中，盖锅盖，小火煎6分钟。' },
      { emoji: '🔄', textId: 'Balik ayam. Tutup lagi. Masak 6 menit dengan api kecil sampai kedua sisi cokelat.', textZh: '翻面，再盖锅盖，小火煎6分钟至两面焦黄。' },
      { emoji: '🍽️', textId: 'Tusuk ayam dengan garpu. Kalau tidak ada darah keluar, berarti sudah matang. Matikan api. Sajikan.', textZh: '用叉子戳鸡肉，没有血水流出就是熟了，关火出锅。' },
    ],
    tipId: 'Pakai api kecil supaya ayam matang sampai ke dalam dan tidak gosong.',
    tipZh: '用小火煎，里面才熟、外皮不糊。',
  },
  {
    id: 'steamed-pomfret',
    nameZh: '清蒸白鲳',
    nameId: 'Tim Ikan Bawal',
    emoji: '🐟',
    category: 'fish',
    timeMin: 20,
    difficulty: 1,
    ingredients: [
      { key: 'pomfret',  qty: 1 },
      { key: 'ginger',   qty: 1 },
      { key: 'scallion', qty: 2 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cuci {pomfret}. Buang isi perutnya. Kerat badan ikan 3 kali di tiap sisi.', textZh: '白鲳洗净去内脏，两面各划3刀。' },
      { emoji: '🧂', textId: 'Lumuri ikan dengan setengah sendok teh garam. Taruh irisan {ginger} di atas ikan.', textZh: '鱼身抹半茶勺盐，姜片铺在鱼上。' },
      { emoji: '💧', textId: 'Didihkan air di kukusan. Masukkan ikan. Kukus 10 menit dengan api besar.', textZh: '蒸锅水烧开后放入鱼，大火蒸10分钟。' },
      { emoji: '🌿', textId: 'Angkat ikan. Buang air di piring. Taburi {scallion} yang sudah dipotong.', textZh: '取出鱼，倒掉盘里的水，撒上葱段。' },
      { emoji: '🥄', textId: 'Tuang 2 sendok makan kecap asin di atas ikan.', textZh: '在鱼身上淋2饭勺生抽。' },
      { emoji: '🔥', textId: 'Panaskan 2 sendok makan minyak sampai sangat panas. Siram ke atas ikan. Sajikan.', textZh: '烧热2饭勺油，浇在鱼身上，上桌。' },
    ],
    tipId: 'Kukus ikan tepat 10 menit saja supaya dagingnya lembut, tidak alot.',
    tipZh: '只蒸10分钟，鱼肉才嫩，久了会老。',
  },
  {
    id: 'fried-pomfret',
    nameZh: '香煎白鲳',
    nameId: 'Ikan Bawal Goreng',
    emoji: '🍳',
    category: 'fish',
    timeMin: 15,
    difficulty: 1,
    ingredients: [
      { key: 'pomfret', qty: 1 },
      { key: 'ginger',  qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cuci {pomfret}. Buang isi perutnya. Kerat badan ikan 3 kali di tiap sisi.', textZh: '白鲳洗净去内脏，两面各划3刀。' },
      { emoji: '🧂', textId: 'Lumuri ikan dengan setengah sendok teh garam dan sedikit merica. Diamkan 10 menit.', textZh: '鱼身抹半茶勺盐和少许胡椒，腌10分钟。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan irisan {ginger}.', textZh: '烧热锅倒2饭勺油，放姜片。' },
      { emoji: '🐟', textId: 'Masukkan ikan. Goreng 4 menit dengan api sedang. Jangan dibalik dulu.', textZh: '放入鱼，中火煎4分钟，先不要翻面。' },
      { emoji: '🔄', textId: 'Balik ikan. Goreng 4 menit lagi sampai kedua sisi keemasan.', textZh: '翻面再煎4分钟，至两面金黄。' },
      { emoji: '🍽️', textId: 'Angkat. Sajikan dengan nasi.', textZh: '盛出，配米饭上桌。' },
    ],
    tipId: 'Balik ikan hanya satu kali supaya kulitnya tidak rusak.',
    tipZh: '只翻一次面，鱼皮才不会破。',
  },
  {
    id: 'braised-hairtail',
    nameZh: '红烧带鱼',
    nameId: 'Ikan Layur Kecap',
    emoji: '🍲',
    category: 'fish',
    timeMin: 25,
    difficulty: 2,
    ingredients: [
      { key: 'hairtail', qty: 8 },
      { key: 'ginger',   qty: 1 },
      { key: 'garlic',   qty: 3 },
      { key: 'scallion', qty: 2 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cuci {hairtail}. Iris {ginger}. Geprek {garlic}.', textZh: '带鱼段洗净，姜切片，蒜拍碎。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Goreng ikan 2 menit tiap sisi sampai keemasan. Angkat.', textZh: '烧热锅倒2饭勺油，鱼段每面煎2分钟至金黄，盛出。' },
      { emoji: '🧄', textId: 'Tuang 1 sendok makan minyak. Masukkan jahe dan bawang putih. Aduk 30 detik.', textZh: '再倒1饭勺油，下姜蒜炒30秒。' },
      { emoji: '🥣', textId: 'Masukkan ikan kembali. Tambah 2 sendok makan kecap asin, 1 sendok makan kecap manis, 1 sendok teh gula, dan setengah mangkuk air.', textZh: '放回鱼段，加2饭勺生抽、1饭勺甜酱油、1茶勺糖和半碗水。' },
      { emoji: '⏲️', textId: 'Tutup wajan. Masak 8 menit dengan api kecil.', textZh: '盖上锅盖，小火煮8分钟。' },
      { emoji: '🔥', textId: 'Buka tutup. Besarkan api. Masak 2 menit sampai kuah kental.', textZh: '开盖转大火，煮2分钟至汤汁浓稠。' },
      { emoji: '🍽️', textId: 'Taburi {scallion} yang sudah dipotong. Angkat. Sajikan.', textZh: '撒上葱段，盛出上桌。' },
    ],
    tipId: 'Goreng ikan dulu supaya tidak hancur saat dimasak dengan kuah.',
    tipZh: '先煎后煮，鱼段才不会散。',
  },
  {
    id: 'fried-hairtail',
    nameZh: '香煎带鱼',
    nameId: 'Ikan Layur Goreng',
    emoji: '🍳',
    category: 'fish',
    timeMin: 20,
    difficulty: 1,
    ingredients: [
      { key: 'hairtail', qty: 8 },
      { key: 'ginger',   qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cuci {hairtail}. Keringkan dengan tisu dapur.', textZh: '带鱼段洗净，用厨房纸擦干。' },
      { emoji: '🧂', textId: 'Lumuri ikan dengan setengah sendok teh garam dan sedikit merica. Diamkan 10 menit.', textZh: '鱼段抹半茶勺盐和少许胡椒，腌10分钟。' },
      { emoji: '🥣', textId: 'Balur ikan dengan 2 sendok makan tepung maizena sampai rata.', textZh: '鱼段均匀裹上2饭勺淀粉。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 3 sendok makan minyak. Masukkan ikan dan irisan {ginger}. Goreng 4 menit dengan api sedang.', textZh: '烧热锅倒3饭勺油，放鱼段和姜片，中火煎4分钟。' },
      { emoji: '🔄', textId: 'Balik ikan. Goreng 4 menit lagi sampai kedua sisi keemasan.', textZh: '翻面再煎4分钟，至两面金黄。' },
      { emoji: '🍽️', textId: 'Angkat. Tiriskan minyaknya. Sajikan.', textZh: '盛出沥油，上桌。' },
    ],
    tipId: 'Baluri tepung supaya kulit ikan renyah dan tidak lengket di wajan.',
    tipZh: '裹层淀粉，鱼皮酥脆还不粘锅。',
  },
  {
    id: 'ginger-squid',
    nameZh: '姜葱炒鱿鱼',
    nameId: 'Tumis Cumi Jahe',
    emoji: '🦑',
    category: 'fish',
    timeMin: 15,
    difficulty: 1,
    ingredients: [
      { key: 'squid',       qty: 3 },
      { key: 'ginger',      qty: 1 },
      { key: 'scallion',    qty: 2 },
      { key: 'bell_pepper', qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cuci {squid}. Potong jadi cincin selebar 1 jari.', textZh: '鱿鱼洗净，切成1指宽的圈。' },
      { emoji: '💧', textId: 'Didihkan air. Rebus cumi 1 menit. Angkat dan tiriskan.', textZh: '烧开水，鱿鱼焯1分钟，捞出沥干。' },
      { emoji: '🫚', textId: 'Iris tipis {ginger}. Potong {scallion} sepanjang 3 cm. Potong {bell_pepper}.', textZh: '姜切丝，葱切3厘米段，青椒切块。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan jahe. Aduk 30 detik.', textZh: '烧热锅倒2饭勺油，下姜丝炒30秒。' },
      { emoji: '🦑', textId: 'Masukkan cumi dan paprika. Aduk 2 menit dengan api besar.', textZh: '下鱿鱼和青椒，大火炒2分钟。' },
      { emoji: '🧂', textId: 'Tambah 1 sendok makan kecap asin dan setengah sendok teh garam. Aduk 1 menit.', textZh: '加1饭勺生抽和半茶勺盐，再炒1分钟。' },
      { emoji: '🍽️', textId: 'Masukkan daun bawang. Aduk sebentar. Matikan api. Angkat.', textZh: '下葱段翻匀，关火盛出。' },
    ],
    tipId: 'Cumi jangan dimasak terlalu lama, nanti keras seperti karet.',
    tipZh: '鱿鱼别炒太久，不然会像橡皮一样硬。',
  },
  {
    id: 'teppan-squid',
    nameZh: '铁板鱿鱼（家常版）',
    nameId: 'Cumi Teppanyaki',
    emoji: '🦑',
    category: 'fish',
    timeMin: 20,
    difficulty: 1,
    ingredients: [
      { key: 'squid',  qty: 3 },
      { key: 'onion',  qty: 1 },
      { key: 'chili',  qty: 2 },
      { key: 'garlic', qty: 3 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cuci {squid}. Potong jadi cincin selebar 1 jari.', textZh: '鱿鱼洗净，切成1指宽的圈。' },
      { emoji: '💧', textId: 'Didihkan air. Rebus cumi 1 menit. Angkat dan tiriskan.', textZh: '烧开水，鱿鱼焯1分钟，捞出沥干。' },
      { emoji: '🧅', textId: 'Iris {onion} dan {chili}. Geprek {garlic}.', textZh: '洋葱和辣椒切丝，蒜拍碎。' },
      { emoji: '🔥', textId: 'Panaskan wajan sampai sangat panas. Tuang 2 sendok makan minyak. Masukkan bawang putih dan cabai. Aduk 30 detik.', textZh: '锅烧到很热，倒2饭勺油，下蒜和辣椒炒30秒。' },
      { emoji: '🦑', textId: 'Masukkan cumi. Aduk 2 menit dengan api besar.', textZh: '下鱿鱼，大火炒2分钟。' },
      { emoji: '🧅', textId: 'Masukkan bawang bombay. Tambah 1 sendok makan kecap asin, 1 sendok makan kecap manis, dan sedikit merica. Aduk 2 menit.', textZh: '下洋葱，加1饭勺生抽、1饭勺甜酱油和少许胡椒，再炒2分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan panas-panas.', textZh: '关火盛出，趁热上桌。' },
    ],
    tipId: 'Api harus besar supaya ada aroma wangi seperti di restoran.',
    tipZh: '火一定要大，才有铁板烧的香味。',
  },
  {
    id: 'fried-mackerel',
    nameZh: '香煎鲅鱼',
    nameId: 'Tenggiri Goreng',
    emoji: '🐟',
    category: 'fish',
    timeMin: 15,
    difficulty: 1,
    ingredients: [
      { key: 'mackerel', qty: 4 },
      { key: 'ginger',   qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cuci {mackerel}. Keringkan dengan tisu dapur.', textZh: '鲅鱼块洗净，用厨房纸擦干。' },
      { emoji: '🧂', textId: 'Lumuri ikan dengan setengah sendok teh garam. Diamkan 10 menit.', textZh: '鱼块抹半茶勺盐，腌10分钟。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan irisan {ginger}.', textZh: '烧热锅倒2饭勺油，放姜片。' },
      { emoji: '🐟', textId: 'Masukkan ikan. Goreng 4 menit dengan api sedang.', textZh: '放入鱼块，中火煎4分钟。' },
      { emoji: '🔄', textId: 'Balik ikan. Goreng 4 menit lagi sampai keemasan dan matang.', textZh: '翻面再煎4分钟，至金黄熟透。' },
      { emoji: '🍽️', textId: 'Angkat. Sajikan. Bisa tambah perasan jeruk nipis kalau suka.', textZh: '盛出上桌，喜欢的话可以挤点柠檬汁。' },
    ],
    tipId: 'Ikan harus kering sebelum digoreng supaya minyak tidak meletup dan kulitnya renyah.',
    tipZh: '鱼擦干再煎，不溅油、皮更脆。',
  },
  {
    id: 'garlic-kangkung',
    nameZh: '蒜蓉空心菜',
    nameId: 'Kangkung Bawang Putih',
    emoji: '🥬',
    category: 'veg',
    timeMin: 10,
    difficulty: 1,
    ingredients: [
      { key: 'kangkung', qty: 1 },
      { key: 'garlic',   qty: 4 },
    ],
    steps: [
      { emoji: '🥬', textId: 'Cuci {kangkung}. Potong sepanjang 5 senti.', textZh: '1把空心菜洗净，切成5厘米长的段。' },
      { emoji: '🧄', textId: 'Geprek {garlic}, lalu potong kecil-kecil.', textZh: '4瓣蒜拍碎切小。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan bawang putih. Aduk 30 detik dengan api sedang sampai wangi.', textZh: '烧热锅倒2饭勺油，下蒜末中火炒30秒至香。' },
      { emoji: '🥬', textId: 'Masukkan kangkung. Aduk 1 menit dengan api besar.', textZh: '下空心菜，大火翻炒1分钟。' },
      { emoji: '🧂', textId: 'Tambah 1 sendok makan saus tiram dan sedikit garam. Aduk 1 menit sampai kangkung layu.', textZh: '加1饭勺蚝油和少许盐，再炒1分钟至空心菜变软。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan.', textZh: '关火出锅上桌。' },
    ],
    tipId: 'Kangkung cepat layu, masak sebentar saja dengan api besar supaya tetap hijau.',
    tipZh: '空心菜很容易软，大火快炒颜色才翠绿。',
  },
  {
    id: 'braised-chicken-wings',
    nameZh: '红烧鸡翅',
    nameId: 'Sayap Ayam Kecap',
    emoji: '🍗',
    category: 'chicken',
    timeMin: 30,
    difficulty: 2,
    ingredients: [
      { key: 'chicken_wing', qty: 8 },
      { key: 'ginger',       qty: 1 },
      { key: 'garlic',       qty: 2 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cuci {chicken_wing}. Sayat 2 kali tiap sayap supaya bumbu masuk.', textZh: '8个鸡翅洗净，每个划2刀方便入味。' },
      { emoji: '💧', textId: 'Rebus 4 mangkuk air di panci. Masukkan sayap. Masak 2 menit. Angkat, buang airnya.', textZh: '锅里煮4碗水，下鸡翅煮2分钟，捞出倒掉水。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 1 sendok makan minyak. Masukkan {ginger} yang sudah diiris dan {garlic} yang sudah digeprek. Aduk 30 detik.', textZh: '烧热锅倒1饭勺油，下姜片（1块姜切片）和拍碎的蒜（2瓣），炒30秒。' },
      { emoji: '🥘', textId: 'Masukkan sayap. Tambah 2 sendok makan kecap manis, 1 sendok makan kecap asin, dan 1 mangkuk air.', textZh: '下鸡翅，加2饭勺甜酱油、1饭勺生抽和1碗水。' },
      { emoji: '⏲️', textId: 'Masak sampai mendidih. Kecilkan api. Tutup wajan. Masak 15 menit.', textZh: '煮开后转小火，盖锅盖煮15分钟。' },
      { emoji: '🔥', textId: 'Buka tutup. Besarkan api. Masak 3 menit sampai kuah kental dan menempel di sayap.', textZh: '开盖转大火，煮3分钟至汤汁浓稠裹住鸡翅。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan.', textZh: '关火出锅上桌。' },
    ],
    tipId: 'Tusuk sayap dengan garpu. Kalau mudah tembus, berarti sudah matang.',
    tipZh: '用叉子戳鸡翅，轻松穿透就是熟了。',
  },
  {
    id: 'braised-fish',
    nameZh: '红烧鱼',
    nameId: 'Ikan Kecap Merah',
    emoji: '🐟',
    category: 'fish',
    timeMin: 30,
    difficulty: 2,
    ingredients: [
      { key: 'fish',     qty: 1 },
      { key: 'ginger',   qty: 2 },
      { key: 'garlic',   qty: 3 },
      { key: 'scallion', qty: 1 },
    ],
    steps: [
      { emoji: '🐟', textId: 'Cuci {fish}. Sayat 3 kali tiap sisi. Keringkan dengan kain bersih.', textZh: '1条鱼洗净，每面划3刀，用干净布擦干。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 3 sendok makan minyak. Masukkan ikan. Goreng 3 menit tiap sisi dengan api sedang sampai kuning. Angkat.', textZh: '烧热锅倒3饭勺油，下鱼每面中火煎3分钟至金黄，盛出。' },
      { emoji: '🧄', textId: 'Tuang 1 sendok makan minyak. Masukkan {ginger} yang sudah diiris dan {garlic} yang sudah digeprek. Aduk 30 detik.', textZh: '倒1饭勺油，下姜片（2块姜切片）和拍碎的蒜（3瓣），炒30秒。' },
      { emoji: '🥘', textId: 'Masukkan ikan kembali. Tambah 2 sendok makan kecap asin, 1 sendok makan kecap manis, dan 1 mangkuk air.', textZh: '放回鱼，加2饭勺生抽、1饭勺甜酱油和1碗水。' },
      { emoji: '⏲️', textId: 'Masak sampai mendidih. Kecilkan api. Tutup wajan. Masak 8 menit.', textZh: '煮开后转小火，盖锅盖煮8分钟。' },
      { emoji: '🔥', textId: 'Buka tutup. Besarkan api. Masak 2 menit sampai kuah kental.', textZh: '开盖转大火，煮2分钟至汤汁浓稠。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Taburi {scallion} yang sudah dipotong kecil. Sajikan.', textZh: '关火出锅，撒上切好的葱花（1根），上桌。' },
    ],
    tipId: 'Balik ikan hanya sekali supaya tidak hancur.',
    tipZh: '鱼只翻一次面，才不会散。',
  },
  {
    id: 'broccoli-shrimp',
    nameZh: '西兰花炒虾仁',
    nameId: 'Tumis Brokoli dan Udang',
    emoji: '🥦',
    category: 'shrimp',
    timeMin: 15,
    difficulty: 1,
    ingredients: [
      { key: 'broccoli', qty: 1 },
      { key: 'shrimp',   qty: 8 },
      { key: 'garlic',   qty: 2 },
    ],
    steps: [
      { emoji: '🦐', textId: 'Cuci {shrimp}. Kupas dan buang kulitnya.', textZh: '8只虾洗净，剥掉虾壳。' },
      { emoji: '🥦', textId: 'Cuci {broccoli}. Potong jadi kuntum-kuntum kecil.', textZh: '1个西兰花洗净，切成小朵。' },
      { emoji: '💧', textId: 'Rebus 3 mangkuk air di panci. Masukkan brokoli. Masak 2 menit. Angkat dan tiriskan.', textZh: '锅里煮3碗水，下西兰花煮2分钟，捞出沥干。' },
      { emoji: '🔥', textId: 'Geprek {garlic}. Panaskan wajan, tuang 2 sendok makan minyak. Masukkan bawang putih. Aduk 30 detik dengan api sedang.', textZh: '2瓣蒜拍碎。烧热锅倒2饭勺油，下蒜中火炒30秒。' },
      { emoji: '🦐', textId: 'Masukkan udang. Masak 2 menit dengan api besar sampai berwarna merah.', textZh: '下虾仁，大火炒2分钟至变红。' },
      { emoji: '🥦', textId: 'Masukkan brokoli. Tambah 1 sendok makan saus tiram dan sedikit garam. Aduk 1 menit.', textZh: '下西兰花，加1饭勺蚝油和少许盐，翻炒1分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan.', textZh: '关火出锅上桌。' },
    ],
    tipId: 'Udang dimasak sebentar saja supaya tidak keras.',
    tipZh: '虾仁稍炒就好，炒老了会硬。',
  },
  {
    id: 'cabbage-egg',
    nameZh: '包菜炒鸡蛋',
    nameId: 'Telur Orak-arik Kol',
    emoji: '🥬',
    category: 'egg',
    timeMin: 15,
    difficulty: 1,
    ingredients: [
      { key: 'cabbage', qty: 4 },
      { key: 'egg',     qty: 3 },
      { key: 'garlic',  qty: 2 },
    ],
    steps: [
      { emoji: '🥬', textId: 'Sobek {cabbage} kecil-kecil dengan tangan. Cuci bersih. Tiriskan.', textZh: '4片包菜用手撕成小块，洗净沥干。' },
      { emoji: '🥚', textId: 'Pecahkan {egg} ke dalam mangkuk. Tambah sedikit garam. Kocok dengan garpu selama 30 detik.', textZh: '3个鸡蛋打入碗里，加一点盐，用叉子搅30秒。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan telur. Aduk sampai matang. Angkat ke piring.', textZh: '烧热锅倒2饭勺油，下蛋液炒熟，盛出。' },
      { emoji: '🧄', textId: 'Geprek {garlic}. Tuang 1 sendok makan minyak ke wajan. Masukkan bawang putih. Aduk 30 detik.', textZh: '2瓣蒜拍碎。锅里倒1饭勺油，下蒜炒30秒。' },
      { emoji: '🥬', textId: 'Masukkan kol. Aduk 2 menit dengan api besar.', textZh: '下包菜，大火翻炒2分钟。' },
      { emoji: '🍳', textId: 'Masukkan telur kembali. Tambah 1 sendok makan kecap asin. Aduk 1 menit. Matikan api. Sajikan.', textZh: '倒回鸡蛋，加1饭勺生抽，翻炒1分钟，关火出锅。' },
    ],
    tipId: 'Kol dimasak dengan api besar supaya tetap renyah.',
    tipZh: '包菜大火快炒，保持脆口。',
  },
  {
    id: 'garlic-greens',
    nameZh: '蒜蓉青菜',
    nameId: 'Sawi Bawang Putih',
    emoji: '🥬',
    category: 'veg',
    timeMin: 10,
    difficulty: 1,
    ingredients: [
      { key: 'greens', qty: 1 },
      { key: 'garlic', qty: 4 },
    ],
    steps: [
      { emoji: '🥬', textId: 'Cuci {greens}. Potong jadi 2 bagian tiap batang.', textZh: '1把青菜洗净，每根切成2段。' },
      { emoji: '🧄', textId: 'Geprek {garlic}, lalu potong kecil-kecil.', textZh: '4瓣蒜拍碎切小。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan bawang putih. Aduk 30 detik dengan api sedang sampai wangi.', textZh: '烧热锅倒2饭勺油，下蒜末中火炒30秒至香。' },
      { emoji: '🥬', textId: 'Masukkan sawi. Aduk 1 menit dengan api besar.', textZh: '下青菜，大火翻炒1分钟。' },
      { emoji: '🧂', textId: 'Tambah 1 sendok makan saus tiram dan sedikit garam. Aduk 1 menit sampai sawi layu.', textZh: '加1饭勺蚝油和少许盐，再炒1分钟至青菜变软。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan.', textZh: '关火出锅上桌。' },
    ],
    tipId: 'Masukkan saus tiram di akhir supaya sayur tetap hijau dan wangi.',
    tipZh: '蚝油最后放，青菜颜色绿、味道鲜。',
  },
  {
    id: 'beans-minced-pork',
    nameZh: '肉末四季豆',
    nameId: 'Buncis Daging Cincang',
    emoji: '🫛',
    category: 'veg',
    timeMin: 20,
    difficulty: 1,
    ingredients: [
      { key: 'green_beans', qty: 15 },
      { key: 'minced_pork', qty: 1 },
      { key: 'garlic',      qty: 2 },
    ],
    steps: [
      { emoji: '🫛', textId: 'Cuci {green_beans}. Buang ujungnya. Potong kecil sepanjang 1 senti.', textZh: '15根四季豆洗净去两头，切成1厘米长的小段。' },
      { emoji: '🧄', textId: 'Geprek {garlic}, lalu potong kecil-kecil.', textZh: '2瓣蒜拍碎切小。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan buncis. Masak 5 menit dengan api sedang sampai kulitnya keriput. Angkat.', textZh: '烧热锅倒2饭勺油，下四季豆中火炒5分钟至表皮起皱，盛出。' },
      { emoji: '🐷', textId: 'Tuang 1 sendok makan minyak. Masukkan bawang putih dan {minced_pork}. Aduk 2 menit dengan api sedang sampai daging berubah warna.', textZh: '倒1饭勺油，下蒜和1碗猪肉末，中火炒2分钟至变色。' },
      { emoji: '🫛', textId: 'Masukkan buncis kembali. Tambah 1 sendok makan kecap asin dan 1 sendok makan saus tiram. Aduk 2 menit.', textZh: '倒回四季豆，加1饭勺生抽和1饭勺蚝油，翻炒2分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan.', textZh: '关火出锅上桌。' },
    ],
    tipId: 'Buncis harus benar-benar matang. Buncis mentah tidak baik untuk perut.',
    tipZh: '四季豆必须彻底做熟，生的吃了拉肚子。',
  },
  {
    id: 'mushroom-chicken',
    nameZh: '香菇滑鸡',
    nameId: 'Ayam Jamur Empuk',
    emoji: '🍄',
    category: 'chicken',
    timeMin: 25,
    difficulty: 1,
    ingredients: [
      { key: 'chicken_leg', qty: 2 },
      { key: 'mushroom',    qty: 5 },
      { key: 'ginger',      qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Potong {chicken_leg} kecil-kecil, sebesar dadu.', textZh: '2个鸡腿切成小丁。' },
      { emoji: '🧂', textId: 'Taruh ayam di mangkuk. Tambah 1 sendok makan kecap asin dan 1 sendok makan tepung maizena. Aduk rata. Diamkan 10 menit.', textZh: '鸡肉放碗里，加1饭勺生抽和1饭勺淀粉，拌匀，腌10分钟。' },
      { emoji: '🍄', textId: 'Cuci {mushroom}. Potong jadi 2 bagian tiap jamur. Iris {ginger}.', textZh: '5个香菇洗净，每个切成2半；1块姜切片。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan ayam. Masak 3 menit dengan api sedang sampai berubah warna. Angkat.', textZh: '烧热锅倒2饭勺油，下鸡肉中火炒3分钟至变色，盛出。' },
      { emoji: '🍄', textId: 'Tuang 1 sendok makan minyak. Masukkan jahe dan jamur. Masak 2 menit dengan api sedang.', textZh: '倒1饭勺油，下姜片和香菇，中火炒2分钟。' },
      { emoji: '🥘', textId: 'Masukkan ayam kembali. Tambah 1 sendok makan saus tiram dan setengah mangkuk air. Tutup wajan. Masak 5 menit dengan api kecil.', textZh: '倒回鸡肉，加1饭勺蚝油和半碗水，盖锅盖小火焖5分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan.', textZh: '关火出锅上桌。' },
    ],
    tipId: 'Tepung maizena membuat ayam licin dan empuk.',
    tipZh: '淀粉裹过的鸡肉更滑嫩。',
  },
  {
    id: 'corn-shrimp',
    nameZh: '玉米炒虾仁',
    nameId: 'Tumis Jagung dan Udang',
    emoji: '🌽',
    category: 'shrimp',
    timeMin: 15,
    difficulty: 1,
    ingredients: [
      { key: 'corn',   qty: 1 },
      { key: 'shrimp', qty: 8 },
      { key: 'carrot', qty: 1 },
    ],
    steps: [
      { emoji: '🦐', textId: 'Cuci {shrimp}. Kupas dan buang kulitnya.', textZh: '8只虾洗净，剥掉虾壳。' },
      { emoji: '🌽', textId: 'Potong biji {corn} dari batangnya dengan pisau. Kupas {carrot}, potong sebesar dadu kecil.', textZh: '用刀把1根玉米的粒削下来；1根胡萝卜去皮切小丁。' },
      { emoji: '💧', textId: 'Rebus 3 mangkuk air di panci. Masukkan jagung dan wortel. Masak 3 menit. Angkat dan tiriskan.', textZh: '锅里煮3碗水，下玉米粒和胡萝卜丁煮3分钟，捞出沥干。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan udang. Masak 2 menit dengan api besar sampai berwarna merah.', textZh: '烧热锅倒2饭勺油，下虾仁大火炒2分钟至变红。' },
      { emoji: '🌽', textId: 'Masukkan jagung dan wortel. Tambah setengah sendok teh garam dan 1 sendok teh gula. Aduk 1 menit.', textZh: '下玉米粒和胡萝卜丁，加半茶勺盐和1茶勺糖，翻炒1分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan.', textZh: '关火出锅上桌。' },
    ],
    tipId: 'Anak-anak biasanya suka masakan ini karena rasanya manis alami.',
    tipZh: '这道菜有天然甜味，小孩一般都爱吃。',
  },
  {
    id: 'stir-fried-pumpkin',
    nameZh: '清炒南瓜',
    nameId: 'Tumis Labu',
    emoji: '🎃',
    category: 'veg',
    timeMin: 15,
    difficulty: 1,
    ingredients: [
      { key: 'pumpkin', qty: 4 },
      { key: 'garlic',  qty: 2 },
    ],
    steps: [
      { emoji: '🎃', textId: 'Kupas {pumpkin}. Buang bijinya. Potong tipis-tipis.', textZh: '4块南瓜去皮去籽，切成薄片。' },
      { emoji: '🧄', textId: 'Geprek {garlic}, lalu potong kecil-kecil.', textZh: '2瓣蒜拍碎切小。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan bawang putih. Aduk 30 detik dengan api sedang.', textZh: '烧热锅倒2饭勺油，下蒜末中火炒30秒。' },
      { emoji: '🎃', textId: 'Masukkan labu. Aduk 2 menit dengan api sedang.', textZh: '下南瓜，中火翻炒2分钟。' },
      { emoji: '💧', textId: 'Tuang setengah mangkuk air. Tutup wajan. Masak 5 menit dengan api kecil sampai labu lembek.', textZh: '倒半碗水，盖锅盖小火焖5分钟至南瓜软烂。' },
      { emoji: '🍽️', textId: 'Tambah setengah sendok teh garam. Aduk. Matikan api. Angkat. Sajikan.', textZh: '加半茶勺盐，炒匀，关火出锅上桌。' },
    ],
    tipId: 'Potong labu tipis-tipis supaya cepat matang.',
    tipZh: '南瓜切薄一点，熟得快。',
  },
  {
    id: 'braised-winter-melon',
    nameZh: '红烧冬瓜',
    nameId: 'Bligo Kecap Merah',
    emoji: '🍈',
    category: 'veg',
    timeMin: 20,
    difficulty: 2,
    ingredients: [
      { key: 'winter_melon', qty: 4 },
      { key: 'garlic',       qty: 2 },
      { key: 'scallion',     qty: 1 },
    ],
    steps: [
      { emoji: '🍈', textId: 'Kupas {winter_melon}. Potong sebesar dadu besar.', textZh: '4块冬瓜去皮，切成大块。' },
      { emoji: '🧄', textId: 'Geprek {garlic}, lalu potong kecil-kecil.', textZh: '2瓣蒜拍碎切小。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 1 sendok makan minyak. Masukkan bawang putih. Aduk 30 detik dengan api sedang.', textZh: '烧热锅倒1饭勺油，下蒜末中火炒30秒。' },
      { emoji: '🥘', textId: 'Masukkan bligo. Tambah 2 sendok makan kecap asin, 1 sendok makan saus tiram, dan 1 mangkuk air.', textZh: '下冬瓜，加2饭勺生抽、1饭勺蚝油和1碗水。' },
      { emoji: '⏲️', textId: 'Masak sampai mendidih. Kecilkan api. Tutup wajan. Masak 10 menit sampai bligo bening dan lembek.', textZh: '煮开后转小火，盖锅盖煮10分钟至冬瓜透明软烂。' },
      { emoji: '🔥', textId: 'Besarkan api. Masak 2 menit sampai kuah tinggal sedikit.', textZh: '转大火煮2分钟，把汤汁收浓。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Taburi {scallion} yang sudah dipotong kecil. Sajikan.', textZh: '关火出锅，撒上切好的葱花（1根），上桌。' },
    ],
    tipId: 'Bligo yang sudah matang warnanya bening, bukan putih.',
    tipZh: '冬瓜变透明就是熟了，不再是白色。',
  },
  {
    id: 'kungpao-tofu',
    nameZh: '宫保豆腐',
    nameId: 'Tahu Kung Pao',
    emoji: '🌶️',
    category: 'tofu',
    timeMin: 20,
    difficulty: 1,
    ingredients: [
      { key: 'tofu',     qty: 4 },
      { key: 'peanut',   qty: 1 },
      { key: 'garlic',   qty: 2 },
      { key: 'chili',    qty: 2 },
      { key: 'scallion', qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Potong {tofu} sebesar dadu.', textZh: '4块豆腐切成小丁。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 3 sendok makan minyak. Masukkan tahu. Goreng 4 menit dengan api sedang sampai kuning. Angkat.', textZh: '烧热锅倒3饭勺油，下豆腐中火煎4分钟至金黄，盛出。' },
      { emoji: '🧄', textId: 'Geprek {garlic}, potong kecil. Potong {chili} tipis-tipis.', textZh: '2瓣蒜拍碎切小，2个辣椒切细丝。' },
      { emoji: '🌶️', textId: 'Tuang 1 sendok makan minyak. Masukkan bawang putih dan cabai. Aduk 30 detik dengan api sedang.', textZh: '倒1饭勺油，下蒜和辣椒中火炒30秒。' },
      { emoji: '🥘', textId: 'Masukkan tahu kembali. Tambah 1 sendok makan kecap asin, 1 sendok teh gula, dan 1 sendok teh cuka. Aduk pelan 2 menit.', textZh: '倒回豆腐，加1饭勺生抽、1茶勺糖、1茶勺醋，轻轻翻炒2分钟。' },
      { emoji: '🥜', textId: 'Masukkan {peanut}. Aduk 1 menit. Matikan api.', textZh: '下1把花生，翻炒1分钟，关火。' },
      { emoji: '🍽️', textId: 'Angkat. Taburi {scallion} yang sudah dipotong kecil. Sajikan.', textZh: '出锅，撒上切好的葱花（1根），上桌。' },
    ],
    tipId: 'Aduk pelan-pelan supaya tahu tidak hancur.',
    tipZh: '轻轻翻动，豆腐才不会碎。',
  },
  {
    id: 'laver-tofu-soup',
    nameZh: '紫菜豆腐汤',
    nameId: 'Sup Tahu Rumput Laut',
    emoji: '🍲',
    category: 'soup',
    timeMin: 10,
    difficulty: 1,
    ingredients: [
      { key: 'laver',    qty: 2 },
      { key: 'tofu',     qty: 2 },
      { key: 'scallion', qty: 1 },
    ],
    steps: [
      { emoji: '💧', textId: 'Tuang 3 mangkuk air ke panci. Masak dengan api besar sampai mendidih.', textZh: '锅里倒3碗水，大火烧开。' },
      { emoji: '🔪', textId: 'Potong {tofu} sebesar dadu kecil.', textZh: '2块豆腐切成小丁。' },
      { emoji: '🥘', textId: 'Masukkan tahu ke air mendidih. Masak 2 menit.', textZh: '豆腐放入沸水中，煮2分钟。' },
      { emoji: '🍙', textId: 'Sobek {laver} kecil-kecil dengan tangan. Masukkan ke panci. Masak 1 menit.', textZh: '2张紫菜用手撕成小块，下锅煮1分钟。' },
      { emoji: '🧂', textId: 'Tambah 1 sendok teh garam dan sedikit merica. Aduk. Matikan api.', textZh: '加1茶勺盐和少许胡椒，搅匀，关火。' },
      { emoji: '🍽️', textId: 'Taburi {scallion} yang sudah dipotong kecil. Sajikan panas.', textZh: '撒上切好的葱花（1根），趁热上桌。' },
    ],
    tipId: 'Tahu dimasukkan dulu supaya lebih lama menyerap rasa sup.',
    tipZh: '豆腐先下锅，煮久一点更入味。',
  },
  {
    id: 'soy-fried-rice',
    nameZh: '酱油炒饭',
    nameId: 'Nasi Goreng Kecap',
    emoji: '🍚',
    category: 'egg',
    timeMin: 15,
    difficulty: 1,
    ingredients: [
      { key: 'rice',     qty: 2 },
      { key: 'egg',      qty: 2 },
      { key: 'scallion', qty: 1 },
    ],
    steps: [
      { emoji: '🥚', textId: 'Pecahkan {egg} ke dalam mangkuk. Kocok dengan garpu selama 30 detik.', textZh: '2个鸡蛋打入碗里，用叉子搅30秒。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 2 sendok makan minyak. Masukkan telur. Aduk sampai matang. Angkat.', textZh: '烧热锅倒2饭勺油，下蛋液炒熟，盛出。' },
      { emoji: '🍚', textId: 'Tuang 1 sendok makan minyak. Masukkan {rice}. Tekan-tekan dengan sendok supaya tidak menggumpal. Aduk 2 menit dengan api besar.', textZh: '倒1饭勺油，下2碗米饭，用铲子压散不结块，大火翻炒2分钟。' },
      { emoji: '🥢', textId: 'Tambah 2 sendok makan kecap asin dan 1 sendok makan kecap manis. Aduk 1 menit sampai semua nasi berwarna cokelat.', textZh: '加2饭勺生抽和1饭勺甜酱油，翻炒1分钟至米饭全部上色。' },
      { emoji: '🍳', textId: 'Masukkan telur kembali. Aduk 1 menit.', textZh: '倒回鸡蛋，翻炒1分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Taburi {scallion} yang sudah dipotong kecil. Sajikan.', textZh: '关火，撒上切好的葱花（1根），上桌。' },
    ],
    tipId: 'Nasi sisa kemarin dari kulkas lebih enak untuk nasi goreng, tidak lengket.',
    tipZh: '冰箱里的隔夜饭做炒饭更香，不粘。',
  },
  {
    id: 'scallion-oil-noodle',
    nameZh: '葱油拌面',
    nameId: 'Mie Minyak Daun Bawang',
    emoji: '🍜',
    category: 'veg',
    timeMin: 15,
    difficulty: 1,
    ingredients: [
      { key: 'noodles',  qty: 2 },
      { key: 'scallion', qty: 3 },
    ],
    steps: [
      { emoji: '🌿', textId: 'Cuci {scallion}. Potong sepanjang 5 senti.', textZh: '3根葱洗净，切成5厘米长的段。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 4 sendok makan minyak. Masukkan daun bawang. Masak 3 menit dengan api kecil sampai cokelat dan wangi.', textZh: '烧热锅倒4饭勺油，下葱段小火熬3分钟至焦黄飘香。' },
      { emoji: '🥢', textId: 'Angkat daun bawang ke piring. Tambah 2 sendok makan kecap asin dan 1 sendok makan kecap manis ke minyak panas. Aduk. Matikan api.', textZh: '捞出葱段，热油里加2饭勺生抽和1饭勺甜酱油，搅匀，关火。' },
      { emoji: '💧', textId: 'Rebus 4 mangkuk air di panci sampai mendidih. Masukkan {noodles}. Masak 3 menit dengan api sedang.', textZh: '锅里煮4碗水，水开下2个面饼，中火煮3分钟。' },
      { emoji: '🍜', textId: 'Angkat mie. Tiriskan. Taruh di mangkuk besar.', textZh: '捞出面条沥干，放进大碗。' },
      { emoji: '🍽️', textId: 'Siram mie dengan minyak daun bawang. Aduk rata. Taruh daun bawang goreng di atasnya. Sajikan.', textZh: '把葱油浇在面上拌匀，铺上炸过的葱段，上桌。' },
    ],
    tipId: 'Masak daun bawang dengan api kecil supaya tidak gosong dan minyaknya wangi.',
    tipZh: '葱段要用小火熬，不糊、油才香。',
  },
  {
    id: 'cola-ribs',
    nameZh: '可乐排骨',
    nameId: 'Iga Cola',
    emoji: '🥤',
    category: 'pork',
    timeMin: 40,
    difficulty: 1,
    ingredients: [
      { key: 'pork_ribs', qty: 4 },
      { key: 'cola',      qty: 1 },
      { key: 'ginger',    qty: 1 },
    ],
    steps: [
      { emoji: '💧', textId: 'Rebus 4 mangkuk air di panci. Masukkan {pork_ribs}. Masak 3 menit. Angkat dan cuci iga dengan air bersih.', textZh: '锅里煮4碗水，下4块排骨煮3分钟，捞出用清水洗净。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 1 sendok makan minyak. Masukkan iga dan {ginger} yang sudah diiris. Masak 3 menit dengan api sedang.', textZh: '烧热锅倒1饭勺油，下排骨和姜片（1块姜切片），中火炒3分钟。' },
      { emoji: '🥤', textId: 'Tuang {cola} dan 1 sendok makan kecap asin. Masak sampai mendidih.', textZh: '倒1罐可乐和1饭勺生抽，煮开。' },
      { emoji: '⏲️', textId: 'Kecilkan api. Tutup wajan. Masak 25 menit sampai iga empuk.', textZh: '转小火，盖锅盖煮25分钟至排骨软烂。' },
      { emoji: '🔥', textId: 'Buka tutup. Besarkan api. Masak 3 menit sampai kuah kental dan menempel di iga.', textZh: '开盖转大火，煮3分钟至汤汁浓稠裹住排骨。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Sajikan.', textZh: '关火出锅上桌。' },
    ],
    tipId: 'Pakai cola biasa, bukan cola tanpa gula, supaya hasilnya manis dan mengkilap.',
    tipZh: '用普通可乐，不要用无糖可乐，做出来才甜亮。',
  },
  {
    id: 'braised-mackerel',
    nameZh: '红烧鲅鱼',
    nameId: 'Tenggiri Kecap Merah',
    emoji: '🐟',
    category: 'fish',
    timeMin: 30,
    difficulty: 2,
    ingredients: [
      { key: 'mackerel', qty: 4 },
      { key: 'ginger',   qty: 2 },
      { key: 'garlic',   qty: 3 },
      { key: 'scallion', qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cuci {mackerel}. Keringkan dengan kain bersih.', textZh: '4块鲅鱼洗净，用干净布擦干。' },
      { emoji: '🔥', textId: 'Panaskan wajan. Tuang 3 sendok makan minyak. Masukkan ikan. Goreng 3 menit tiap sisi dengan api sedang sampai kuning. Angkat.', textZh: '烧热锅倒3饭勺油，下鱼块每面中火煎3分钟至金黄，盛出。' },
      { emoji: '🧄', textId: 'Tuang 1 sendok makan minyak. Masukkan {ginger} yang sudah diiris dan {garlic} yang sudah digeprek. Aduk 30 detik.', textZh: '倒1饭勺油，下姜片（2块姜切片）和拍碎的蒜（3瓣），炒30秒。' },
      { emoji: '🥘', textId: 'Masukkan ikan kembali. Tambah 2 sendok makan kecap asin, 1 sendok makan kecap manis, dan 1 mangkuk air.', textZh: '放回鱼块，加2饭勺生抽、1饭勺甜酱油和1碗水。' },
      { emoji: '⏲️', textId: 'Masak sampai mendidih. Kecilkan api. Tutup wajan. Masak 8 menit.', textZh: '煮开后转小火，盖锅盖煮8分钟。' },
      { emoji: '🔥', textId: 'Buka tutup. Besarkan api. Masak 2 menit sampai kuah kental.', textZh: '开盖转大火，煮2分钟至汤汁浓稠。' },
      { emoji: '🍽️', textId: 'Matikan api. Angkat. Taburi {scallion} yang sudah dipotong kecil. Sajikan.', textZh: '关火出锅，撒上切好的葱花（1根），上桌。' },
    ],
    tipId: 'Balik ikan hanya sekali supaya tidak hancur.',
    tipZh: '鱼只翻一次面，才不会散。',
  },
];

/* ---------- 中文→印尼语 自定义食材词典 ----------
 * 用户在"其他食材"里输入中文时自动匹配；key 为简体中文名。
 * 预设表里已有的食材会优先匹配预设，不会走到这里。
 */
const ZH_TO_ID = {
  '生菜':   { nameId: 'selada',        unitId: 'buah'    },
  '白菜':   { nameId: 'sawi putih',    unitId: 'buah'    },
  '菠菜':   { nameId: 'bayam',         unitId: 'ikat'    },
  '空心菜': { nameId: 'kangkung',      unitId: 'ikat'    },
  '芹菜':   { nameId: 'seledri',       unitId: 'batang'  },
  '香菜':   { nameId: 'daun ketumbar', unitId: 'ikat'    },
  '豆芽':   { nameId: 'tauge',         unitId: 'genggam' },
  '木耳':   { nameId: 'jamur kuping',  unitId: 'genggam' },
  '金针菇': { nameId: 'jamur enoki',   unitId: 'ikat'    },
  '平菇':   { nameId: 'jamur tiram',   unitId: 'genggam' },
  '口蘑':   { nameId: 'jamur kancing', unitId: 'buah'    },
  '海带':   { nameId: 'rumput laut',   unitId: 'lembar'  },
  '丝瓜':   { nameId: 'oyong',         unitId: 'buah'    },
  '苦瓜':   { nameId: 'pare',          unitId: 'buah'    },
  '秋葵':   { nameId: 'okra',          unitId: 'buah'    },
  '芦笋':   { nameId: 'asparagus',     unitId: 'batang'  },
  '白萝卜': { nameId: 'lobak',         unitId: 'buah'    },
  '红薯':   { nameId: 'ubi jalar',     unitId: 'buah'    },
  '莲藕':   { nameId: 'akar teratai',  unitId: 'ruas'    },
  '红椒':   { nameId: 'paprika merah', unitId: 'buah'    },
  '干辣椒': { nameId: 'cabai kering',  unitId: 'buah'    },
  '排骨':   { nameId: 'iga',           unitId: 'potong'  },
  '五花肉': { nameId: 'babi samcan',   unitId: 'potong'  },
  '肉末':   { nameId: 'daging cincang', unitId: 'mangkuk' },
  '鸡胸肉': { nameId: 'dada ayam',     unitId: 'potong'  },
  '整鸡':   { nameId: 'ayam utuh',     unitId: 'ekor'    },
  '鸭肉':   { nameId: 'bebek',         unitId: 'potong'  },
  '羊肉':   { nameId: 'daging kambing', unitId: 'potong' },
  '猪肝':   { nameId: 'hati babi',     unitId: 'potong'  },
  '鸡爪':   { nameId: 'ceker',         unitId: 'buah'    },
  '鸭蛋':   { nameId: 'telur bebek',   unitId: 'butir'   },
  '鹌鹑蛋': { nameId: 'telur puyuh',   unitId: 'butir'   },
  '螃蟹':   { nameId: 'kepiting',      unitId: 'ekor'    },
  '鱿鱼':   { nameId: 'cumi',          unitId: 'ekor'    },
  '虾仁':   { nameId: 'udang kupas',   unitId: 'ekor'    },
  '蛤蜊':   { nameId: 'kerang',        unitId: 'mangkuk' },
  '粉丝':   { nameId: 'bihun',         unitId: 'keping'  },
  '柠檬':   { nameId: 'jeruk nipis',   unitId: 'buah'    },
  '椰浆':   { nameId: 'santan',        unitId: 'mangkuk' },
};

/* ---------- Node 环境下导出，浏览器里直接是全局变量 ---------- */
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    INGREDIENT_PRESETS, ALWAYS_HAVE, RECIPES, ZH_TO_ID,
    scaledQty, formatQtyId, renderStepId,
  };
}
